In [1]:
import polars as pl

# URL fixa para o release mais recente (Latest)
BASE_URL = "https://github.com/crdcj/pyield-data/releases/latest/download"

# Para ler o arquivo de B3 Futures
filename = "b3_futures.parquet"
df = pl.read_parquet(f"{BASE_URL}/{filename}")
df

shape: (476_786, 17)
┌────────────┬──────────┬───────────┬─────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ TradDt     ┆ TckrSymb ┆ OpnIntrst ┆ TradQty ┆ … ┆ AdjstdQt ┆ AdjstdQtTa ┆ MaxTradLmt ┆ MinTradLm │
│ ---        ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ x          ┆ ---        ┆ t         │
│ date       ┆ str      ┆ i64       ┆ i64     ┆   ┆ f64      ┆ ---        ┆ f64        ┆ ---       │
│            ┆          ┆           ┆         ┆   ┆          ┆ f64        ┆            ┆ f64       │
╞════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 2018-01-02 ┆ DAPF18   ┆ 70855     ┆ 4       ┆ … ┆ 99877.56 ┆ 3.49       ┆ 6.49       ┆ 0.49      │
│ 2018-01-02 ┆ DAPF19   ┆ 700       ┆ null    ┆ … ┆ 97172.53 ┆ 2.83       ┆ 5.81       ┆ -0.19     │
│ 2018-01-02 ┆ DAPG18   ┆ 300       ┆ null    ┆ … ┆ 99629.17 ┆ 3.17       ┆ 6.1        ┆ 0.1       │
│ 2018-01-02 ┆ DAPH18   ┆ null      ┆ null    ┆ … ┆ 99520.9  ┆ 2.45       ┆ 5.42       ┆ -0.58     │
│ 2018-01-02 ┆ DAPK19   ┆ 105039    ┆ 5       ┆ … ┆ 96586.33 ┆ 2.6        ┆ 4.67       ┆ 0.67      │
│ …          ┆ …        ┆ …         ┆ …       ┆ … ┆ …        ┆ …          ┆ …          ┆ …         │
│ 2026-04-01 ┆ WINQ26   ┆ 34749     ┆ 23      ┆ … ┆ 196752.0 ┆ null       ┆ 216105.0   ┆ 176820.0  │
│ 2026-04-01 ┆ WINQ27   ┆ null      ┆ null    ┆ … ┆ 222270.0 ┆ null       ┆ 244250.0   ┆ 199845.0  │
│ 2026-04-01 ┆ WINV26   ┆ null      ┆ null    ┆ … ┆ 200923.0 ┆ null       ┆ 220695.0   ┆ 180575.0  │
│ 2026-04-01 ┆ WINV27   ┆ null      ┆ null    ┆ … ┆ 226316.0 ┆ null       ┆ 248715.0   ┆ 203500.0  │
│ 2026-04-01 ┆ WINZ26   ┆ null      ┆ null    ┆ … ┆ 205151.0 ┆ null       ┆ 225360.0   ┆ 184390.0  │
└────────────┴──────────┴───────────┴─────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [3]:
df["TradDt"].unique()

shape: (2_047,)
Series: 'TradDt' [date]
[
	2018-01-02
	2018-01-03
	2018-01-04
	2018-01-05
	2018-01-08
	…
	2026-03-24
	2026-03-25
	2026-03-26
	2026-03-27
	2026-03-30
]

In [2]:
df.columns

['TradDt',
 'TckrSymb',
 'OpnIntrst',
 'TradQty',
 'FinInstrmQty',
 'NtlFinVol',
 'BestBidPric',
 'BestAskPric',
 'FrstPric',
 'MinPric',
 'MaxPric',
 'TradAvrgPric',
 'LastPric',
 'AdjstdQt',
 'AdjstdQtTax',
 'MaxTradLmt',
 'MinTradLmt']

In [8]:
df.write_parquet(filename)