In [2]:
import pandas as pd

In [5]:
df = pd.read_parquet("../anbima_data.parquet")
df

       BondType ReferenceDate MaturityDate  IndicativeRate
0           LFT    2007-01-02   2007-01-10        -0.00015
1           LFT    2007-01-02   2007-01-17       -0.000149
2           LFT    2007-01-02   2007-02-14       -0.000154
3           LFT    2007-01-02   2007-02-21        -0.00015
4           LFT    2007-01-02   2007-03-14       -0.000148
...         ...           ...          ...             ...
220759    NTN-F    2024-12-30   2027-01-01        0.159428
220760    NTN-F    2024-12-30   2029-01-01         0.15911
220761    NTN-F    2024-12-30   2031-01-01        0.156813
220762    NTN-F    2024-12-30   2033-01-01        0.154176
220763    NTN-F    2024-12-30   2035-01-01        0.152095

[220764 rows x 4 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220764 entries, 0 to 220763
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   BondType        220764 non-null  string
 1   ReferenceDate   220764 non-null  datetime64[ns]
 2   MaturityDate    220764 non-null  datetime64[ns]
 3   IndicativeRate  220764 non-null  Float64
dtypes: Float64(1), datetime64[ns](2), string(1)
memory usage: 6.9 MB

In [7]:
rdate = pd.Timestamp("2024-12-23")

df = df.query("ReferenceDate == @rdate").reset_index(drop=True)
df

   BondType ReferenceDate MaturityDate  IndicativeRate
0       LFT    2024-12-23   2025-03-01        0.000253
1       LFT    2024-12-23   2025-09-01        0.000243
2       LFT    2024-12-23   2026-03-01        0.000329
3       LFT    2024-12-23   2026-09-01        0.000344
4       LFT    2024-12-23   2027-03-01        0.000762
5       LFT    2024-12-23   2027-09-01         0.00089
6       LFT    2024-12-23   2028-03-01        0.000925
7       LFT    2024-12-23   2028-09-01        0.001106
8       LFT    2024-12-23   2029-03-01        0.001321
9       LFT    2024-12-23   2029-09-01        0.001352
10      LFT    2024-12-23   2030-03-01        0.001343
11      LFT    2024-12-23   2030-06-01        0.001343
12      LFT    2024-12-23   2030-09-01        0.001342
13      LFT    2024-12-23   2030-12-01        0.001321
14      LTN    2024-12-23   2025-01-01        0.122439
15      LTN    2024-12-23   2025-04-01         0.13076
16      LTN    2024-12-23   2025-07-01        0.141044
17      LTN    2024-12-23   2025-10-01        0.148548
18      LTN    2024-12-23   2026-01-01        0.152517
19      LTN    2024-12-23   2026-04-01        0.154866
20      LTN    2024-12-23   2026-07-01        0.155644
21      LTN    2024-12-23   2026-10-01        0.155347
22      LTN    2024-12-23   2027-07-01        0.153935
23      LTN    2024-12-23   2028-01-01        0.152673
24      LTN    2024-12-23   2028-07-01          0.1517
25      LTN    2024-12-23   2030-01-01         0.14953
26    NTN-B    2024-12-23   2025-05-15        0.046475
27    NTN-B    2024-12-23   2026-08-15        0.080361
28    NTN-B    2024-12-23   2027-05-15        0.080026
29    NTN-B    2024-12-23   2028-08-15        0.079863
30    NTN-B    2024-12-23   2029-05-15         0.07701
31    NTN-B    2024-12-23   2030-08-15        0.075622
32    NTN-B    2024-12-23   2032-08-15          0.0753
33    NTN-B    2024-12-23   2033-05-15        0.075039
34    NTN-B    2024-12-23   2035-05-15           0.074
35    NTN-B    2024-12-23   2040-08-15        0.071147
36    NTN-B    2024-12-23   2045-05-15        0.071861
37    NTN-B    2024-12-23   2050-08-15        0.072327
38    NTN-B    2024-12-23   2055-05-15        0.072263
39    NTN-B    2024-12-23   2060-08-15        0.072101
40    NTN-C    2024-12-23   2031-01-01        0.067975
41    NTN-F    2024-12-23   2025-01-01        0.122483
42    NTN-F    2024-12-23   2027-01-01        0.154319
43    NTN-F    2024-12-23   2029-01-01        0.151355
44    NTN-F    2024-12-23   2031-01-01          0.1487
45    NTN-F    2024-12-23   2033-01-01        0.145836
46    NTN-F    2024-12-23   2035-01-01        0.144064

In [8]:
rdate = pd.Timestamp("2024-12-24")

df.query("ReferenceDate == @rdate")

Empty DataFrame
Columns: [BondType, ReferenceDate, MaturityDate, IndicativeRate]
Index: []

In [28]:
# df.to_parquet("../anbima_data.parquet", index=False, compression="gzip")

In [9]:
df = pd.read_parquet("../di_data.parquet")
df

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,DV01,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,1995-01-02,1995-02-01,DI1FEV5,22,185169,340,45045,2180001225,0.56255,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,1995-01-02,1995-03-01,DI1MAR5,40,12145,21,1590,74621000,1.019868,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,1995-01-02,1995-04-03,DI1ABR5,63,150,0,0,0,1.636827,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,1995-01-03,1995-02-01,DI1FEV5,21,193594,427,81175,3932939112,0.530598,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,1995-01-03,1995-03-01,DI1MAR5,39,12295,96,13425,630682950,0.966267,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214923,2024-12-30,2035-01-02,DI1F35,2506,307045,10307,38442,966378537,21.590782,0.1483,0.1469,0.14895,0.1502,0.1494,<NA>,0.1493,0.14976,24962.9
214924,2024-12-30,2036-01-02,DI1F36,2755,21911,558,2285,50164339,20.855494,0.1476,0.1476,0.14876,0.1493,0.1492,<NA>,0.1485,0.14894,21917.79
214925,2024-12-30,2037-01-02,DI1F37,3008,4714,205,992,19152141,20.01657,0.1465,0.1464,0.14773,0.1482,0.1482,0.1485,<NA>,0.14801,19251.21
214926,2024-12-30,2038-01-04,DI1F38,3257,3976,725,2954,50167042,19.099355,0.1453,0.1453,0.14703,0.1475,0.1471,<NA>,<NA>,0.14719,16952.62
214927,2024-12-30,2039-01-03,DI1F39,3508,5041,11,326,4834756,17.941624,0.1474,0.1469,0.14693,0.1474,0.1469,<NA>,<NA>,0.14719,14785.57

In [19]:
df.query("TradeDate == TradeDate.max()")
df.query("TradeDate == @rdate")

Empty DataFrame
Columns: [TradeDate, ExpirationDate, TickerSymbol, BDaysToExp, OpenContracts, TradeCount, TradeVolume, FinancialVolume, DV01, OpenRate, MinRate, AvgRate, MaxRate, CloseRate, CloseBidRate, CloseAskRate, SettlementRate, SettlementPrice]
Index: []

In [ ]:
# df.to_parquet("../di_data.parquet", index=False, compression="gzip")