In [1]:
import pandas as pd

df = pd.read_parquet("../data/anbima_tpf.parquet")
df

,BondType,ReferenceDate,SelicCode,IssueBaseDate,MaturityDate,BDToMat,Duration,DV01,DV01USD,Price,BidRate,AskRate,IndicativeRate,DIRate
0,LFT,2020-01-02,210100,2000-07-01,2020-03-01,40,0.0,0.0,0.0,10471.849015,<NA>,<NA>,0.000023,0.04375
1,LFT,2020-01-02,210100,2000-07-01,2020-09-01,167,0.0,0.0,0.0,10471.723352,<NA>,<NA>,0.000023,0.04344
2,LFT,2020-01-02,210100,2000-07-01,2021-03-01,289,0.0,0.0,0.0,10471.356836,<NA>,<NA>,0.000044,0.046359
3,LFT,2020-01-02,210100,2000-07-01,2021-09-01,418,0.0,0.0,0.0,10470.917017,<NA>,<NA>,0.000056,0.050221
4,LFT,2020-01-02,210100,2000-07-01,2022-03-01,542,0.0,0.0,0.0,10470.016434,<NA>,<NA>,0.000083,0.053607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63857,NTN-F,2025-08-26,950199,2016-01-15,2027-01-01,339,1.275077,0.108567,0.020025,970.195537,0.139582,0.139328,0.13946,0.1398
63858,NTN-F,2025-08-26,950199,2018-01-05,2029-01-01,838,2.853494,0.234469,0.043248,931.709383,0.133983,0.133781,0.133895,0.13246
63859,NTN-F,2025-08-26,950199,2020-01-10,2031-01-01,1339,4.108755,0.318707,0.058786,882.82519,0.138196,0.138064,0.138133,0.13587
63860,NTN-F,2025-08-26,950199,2022-01-07,2033-01-01,1843,5.089522,0.379147,0.069934,848.53246,0.139154,0.13895,0.139038,0.13768
63861,NTN-F,2025-08-26,950199,2024-01-05,2035-01-01,2342,5.823301,0.418689,0.077228,819.856662,0.140404,0.140214,0.14029,0.13804

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63862 entries, 0 to 63861
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BondType        63862 non-null  string
 1   ReferenceDate   63862 non-null  date32[day][pyarrow]
 2   SelicCode       63862 non-null  int64[pyarrow]
 3   IssueBaseDate   63862 non-null  date32[day][pyarrow]
 4   MaturityDate    63862 non-null  date32[day][pyarrow]
 5   BDToMat         63862 non-null  int64[pyarrow]
 6   Duration        63862 non-null  double[pyarrow]
 7   DV01            63862 non-null  double[pyarrow]
 8   DV01USD         63862 non-null  double[pyarrow]
 9   Price           63862 non-null  double[pyarrow]
 10  BidRate         61041 non-null  double[pyarrow]
 11  AskRate         61038 non-null  double[pyarrow]
 12  IndicativeRate  63862 non-null  double[pyarrow]
 13  DIRate          63862 non-null  double[pyarrow]
dtypes: date32[day][pyarrow](3), double[pyarrow](8), int64[pyarrow](2), string(1)
memory usage: 6.4 MB

In [3]:
df["BondType"] = df["BondType"].astype("string[pyarrow]")

In [11]:
rdate = pd.to_datetime("03-01-2024", dayfirst=True)
df.query("ReferenceDate == @rdate").reset_index(drop=True)

,BondType,ReferenceDate,SelicCode,IssueBaseDate,MaturityDate,BDToMat,Duration,DV01,DV01USD,Price,BidRate,AskRate,IndicativeRate,DIRate,StdDev,LowerBoundRateD0,UpperBoundRateD0,LowerBoundRateD1,UpperBoundRateD1,Criteria
0,LFT,2024-01-03,210100,2000-07-01,2024-03-01,40,0.0,0.0,0.0,14282.392313,-0.000076,-0.000264,-0.00016,0.11407,0.008062,-0.00035,0.000257,-0.000489,0.000118,Calculado
1,LFT,2024-01-03,210100,2000-07-01,2024-09-01,168,0.0,0.0,0.0,14283.334928,-0.000075,-0.000255,-0.000137,0.10453,0.008949,-0.000343,0.000104,-0.000413,0.000001,Calculado
2,LFT,2024-01-03,210100,2000-07-01,2025-03-01,294,0.0,0.0,0.0,14281.792468,0.000028,0.000006,0.000014,0.099144,0.001106,-0.000126,0.000176,-0.000221,0.000158,Calculado
3,LFT,2024-01-03,210100,2000-07-01,2025-09-01,418,0.0,0.0,0.0,14278.193395,0.000203,0.000126,0.000162,0.097158,0.003252,0.000073,0.000451,0.000025,0.00043,Calculado
4,LFT,2024-01-03,210100,2000-07-01,2026-03-01,543,0.0,0.0,0.0,14269.381379,0.000429,0.000399,0.000411,0.096796,0.001709,0.000329,0.00074,0.000308,0.000713,Calculado
5,LFT,2024-01-03,210100,2000-07-01,2026-09-01,670,0.0,0.0,0.0,14254.499499,0.00074,0.000704,0.000726,0.097417,0.001447,0.000646,0.000983,0.000617,0.000974,Calculado
6,LFT,2024-01-03,210100,2000-07-01,2027-03-01,791,0.0,0.0,0.0,14228.092015,0.001218,0.001184,0.001206,0.098001,0.000804,0.000771,0.001354,0.000752,0.001339,Calculado
7,LFT,2024-01-03,210100,2000-07-01,2027-09-01,920,0.0,0.0,0.0,14214.195595,0.001316,0.00129,0.001305,0.099235,0.000706,0.001098,0.001448,0.00108,0.001436,Calculado
8,LFT,2024-01-03,210100,2000-07-01,2028-03-01,1044,0.0,0.0,0.0,14201.013276,0.001383,0.001353,0.001374,0.10027,0.000784,0.001281,0.001567,0.001268,0.001554,Calculado
9,LFT,2024-01-03,210100,2000-07-01,2028-09-01,1172,0.0,0.0,0.0,14183.931962,0.001497,0.001458,0.001483,0.101167,0.000811,0.001385,0.00169,0.001374,0.001679,Calculado
10,LFT,2024-01-03,210100,2000-07-01,2029-03-01,1292,0.0,0.0,0.0,14165.008266,0.00162,0.001584,0.001606,0.101678,0.000674,0.001489,0.001704,0.001479,0.001698,Calculado
11,LFT,2024-01-03,210100,2000-07-01,2029-09-01,1421,0.0,0.0,0.0,14147.727003,0.001682,0.001671,0.001677,0.102325,0.000257,0.001469,0.001766,0.001464,0.001764,Calculado
12,LTN,2024-01-03,100000,2022-01-07,2024-04-01,60,0.238095,0.020899,0.004247,975.242313,0.111554,0.110887,0.111034,0.11272,0.026469,0.109994,0.111629,0.110278,0.11195,Calculado
13,LTN,2024-01-03,100000,2021-01-08,2024-07-01,123,0.488095,0.042008,0.008537,951.969879,0.106521,0.105803,0.106105,0.10761,0.015977,0.104222,0.107414,0.104544,0.107702,Calculado
14,LTN,2024-01-03,100000,2022-07-08,2024-10-01,189,0.75,0.063324,0.012868,930.039876,0.101968,0.101203,0.101534,0.10321,0.040599,0.098609,0.10367,0.099075,0.104121,Calculado
15,LTN,2024-01-03,100000,2018-02-01,2025-01-01,252,1.0,0.082852,0.016837,910.230351,0.099028,0.09837,0.098623,0.10039,0.040576,0.095161,0.101058,0.095555,0.101438,Calculado
16,LTN,2024-01-03,100000,2023-01-06,2025-04-01,313,1.242063,0.100582,0.02044,889.698208,0.098725,0.09859,0.098665,0.09869,0.005249,0.095218,0.101777,0.095414,0.101963,Calculado
17,LTN,2024-01-03,100000,2022-01-07,2025-07-01,374,1.484127,0.117709,0.02392,870.685519,0.097864,0.097722,0.097795,0.09753,0.002722,0.094252,0.101337,0.094339,0.101414,Calculado
18,LTN,2024-01-03,100000,2023-07-07,2025-10-01,440,1.746032,0.135229,0.027481,850.027672,0.097586,0.097477,0.097528,0.097,0.00048,0.093564,0.101186,0.093751,0.101366,Calculado
19,LTN,2024-01-03,100000,2020-02-03,2026-01-01,504,2.0,0.151437,0.030774,830.745476,0.09725,0.09708,0.09715,0.09645,0.0,0.092787,0.100767,0.092939,0.100915,Calculado
20,LTN,2024-01-03,100000,2023-01-06,2026-07-01,626,2.484127,0.179379,0.036453,792.83506,0.098017,0.097886,0.097955,0.09704,0.002499,0.09339,0.101714,0.093518,0.101842,Calculado
21,LTN,2024-01-03,100000,2023-07-07,2027-07-01,876,3.47619,0.226996,0.046129,718.229917,0.099952,0.099811,0.099889,0.09875,0.001499,0.095007,0.103373,0.095206,0.103572,Calculado
22,NTN-B,2024-01-03,760199,2000-07-15,2024-08-15,156,0.604542,0.242212,0.049221,4266.019173,0.064929,0.064629,0.064763,0.105316,0.003791,0.06156,0.072567,0.05994,0.071023,Calculado
23,NTN-B,2024-01-03,760199,2000-07-15,2025-05-15,342,1.31546,0.529969,0.107698,4247.937379,0.054592,0.054255,0.0544,0.098087,0.0,0.051827,0.057844,0.051182,0.057197,Calculado
24,NTN-B,2024-01-03,760199,2000-07-15,2026-08-15,659,2.411104,0.9994,0.203093,4359.557528,0.051938,0.051666,0.051766,0.097327,0.004585,0.049442,0.054411,0.049108,0.054078,Calculado
25,NTN-B,2024-01-03,760199,2000-07-15,2027-05-15,844,3.068411,1.256854,0.255411,4311.562537,0.052806,0.05247,0.0526,0.098481,0.0,0.049915,0.054705,0.049846,0.054636,Calculado
26,NTN-B,2024-01-03,760199,2000-07-15,2028-08-15,1159,4.015484,1.682551,0.341919,4409.17578,0.05243,0.052108,0.05227,0.101104,0.003429,0.049538,0.054431,0.049608,0.0545,Calculado
27,NTN-B,2024-01-03,760199,2000-07-15,2030-08-15,1657,5.44891,2.310404,0.469508,4461.454842,0.052346,0.052053,0.0522,0.103318,0.0,0.049629,0.054285,0.049711,0.054368,Calculado
28,NTN-B,2024-01-03,760199,2000-07-15,2032-08-15,2161,6.744128,2.865513,0.582315,4474.993178,0.05336,0.05302,0.053212,0.104392,0.001978,0.050785,0.055131,0.050896,0.055242,Calculado
29,NTN-B,2024-01-03,760199,2000-07-15,2033-05-15,2348,7.292388,3.067133,0.623287,4429.449814,0.053318,0.052957,0.053142,0.104658,0.006538,0.050733,0.054976,0.050898,0.055141,Calculado
30,NTN-B,2024-01-03,760199,2000-07-15,2035-05-15,2847,8.416297,3.556882,0.722811,4452.200578,0.053624,0.053339,0.05348,0.104933,0.002812,0.051193,0.055202,0.051372,0.055381,Calculado
31,NTN-B,2024-01-03,760199,2000-07-15,2040-08-15,4166,10.732013,4.65477,0.945918,4570.338875,0.053906,0.05357,0.053735,0.10516,0.004383,0.051774,0.0554,0.051838,0.055464,Calculado
32,NTN-B,2024-01-03,760199,2000-07-15,2045-05-15,5353,12.539209,5.348366,1.086867,4499.070163,0.055003,0.054654,0.054804,0.10516,0.001179,0.052974,0.056416,0.053,0.056442,Calculado
33,NTN-B,2024-01-03,760199,2000-07-15,2050-08-15,6668,13.80965,6.015098,1.222357,4594.344737,0.054951,0.05462,0.054784,0.10516,0.002263,0.053038,0.056355,0.053044,0.056361,Calculado
34,NTN-B,2024-01-03,760199,2000-07-15,2055-05-15,7857,15.015636,6.484286,1.317703,4555.001564,0.055007,0.054621,0.0548,0.10516,0.0,0.053072,0.056314,0.053101,0.056344,Calculado
35,NTN-B,2024-01-03,760199,2000-07-15,2060-08-15,9174,15.665698,6.868093,1.395699,4625.061197,0.055172,0.054775,0.054948,0.10516,0.00413,0.053274,0.056459,0.053277,0.056463,Calculado
36,NTN-C,2024-01-03,770100,2000-07-01,2031-01-01,1753,5.254073,4.142152,0.841747,8319.419694,0.056589,0.0539,0.055269,0.10366,0.049988,0.051098,0.059329,0.050916,0.059135,Calculado
37,NTN-F,2024-01-03,950199,2014-01-10,2025-01-01,252,0.976165,0.088954,0.018077,1001.206109,0.099193,0.098456,0.098702,0.10039,0.026189,0.095554,0.101382,0.095674,0.101489,Calculado
38,NTN-F,2024-01-03,950199,2016-01-15,2027-01-01,753,2.661286,0.243122,0.049406,1003.857578,0.098954,0.098687,0.098851,0.09763,0.006805,0.094179,0.102445,0.094295,0.102561,Calculado
39,NTN-F,2024-01-03,950199,2018-01-05,2029-01-01,1252,4.045288,0.365373,0.074249,995.2765,0.102011,0.101848,0.101938,0.10145,0.001794,0.097144,0.105282,0.097443,0.10558,Calculado
40,NTN-F,2024-01-03,950199,2020-01-10,2031-01-01,1753,5.182749,0.462308,0.093948,984.719625,0.104026,0.103806,0.103929,0.10366,0.004724,0.098935,0.106996,0.099438,0.107496,Calculado
41,NTN-F,2024-01-03,950199,2022-01-07,2033-01-01,2257,6.117925,0.54113,0.109966,977.127029,0.1048,0.104642,0.104724,0.10465,0.002793,0.099577,0.107509,0.100322,0.10825,Calculado

In [13]:
select_cols = [
    "BondType",
    "ReferenceDate",
    "SelicCode",
    "IssueBaseDate",
    "MaturityDate",
    "BDToMat",
    "Duration",
    "DV01",
    "DV01USD",
    "Price",
    "BidRate",
    "AskRate",
    "IndicativeRate",
    "DIRate",
]
df = df[select_cols].copy()
df

,BondType,ReferenceDate,SelicCode,IssueBaseDate,MaturityDate,BDToMat,Duration,DV01,DV01USD,Price,BidRate,AskRate,IndicativeRate,DIRate
0,LFT,2020-01-02,210100,2000-07-01,2020-03-01,40,0.0,0.0,0.0,10471.849015,<NA>,<NA>,0.000023,0.04375
1,LFT,2020-01-02,210100,2000-07-01,2020-09-01,167,0.0,0.0,0.0,10471.723352,<NA>,<NA>,0.000023,0.04344
2,LFT,2020-01-02,210100,2000-07-01,2021-03-01,289,0.0,0.0,0.0,10471.356836,<NA>,<NA>,0.000044,0.046359
3,LFT,2020-01-02,210100,2000-07-01,2021-09-01,418,0.0,0.0,0.0,10470.917017,<NA>,<NA>,0.000056,0.050221
4,LFT,2020-01-02,210100,2000-07-01,2022-03-01,542,0.0,0.0,0.0,10470.016434,<NA>,<NA>,0.000083,0.053607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63857,NTN-F,2025-08-26,950199,2016-01-15,2027-01-01,339,1.275077,0.108567,0.020025,970.195537,0.139582,0.139328,0.13946,0.1398
63858,NTN-F,2025-08-26,950199,2018-01-05,2029-01-01,838,2.853494,0.234469,0.043248,931.709383,0.133983,0.133781,0.133895,0.13246
63859,NTN-F,2025-08-26,950199,2020-01-10,2031-01-01,1339,4.108755,0.318707,0.058786,882.82519,0.138196,0.138064,0.138133,0.13587
63860,NTN-F,2025-08-26,950199,2022-01-07,2033-01-01,1843,5.089522,0.379147,0.069934,848.53246,0.139154,0.13895,0.139038,0.13768
63861,NTN-F,2025-08-26,950199,2024-01-05,2035-01-01,2342,5.823301,0.418689,0.077228,819.856662,0.140404,0.140214,0.14029,0.13804

In [5]:
df.to_parquet("../data/anbima_tpf.parquet", index=False, compression="gzip")