In [1]:
import pandas as pd

df = pd.read_parquet("../data/anbima_tpf.parquet", dtype_backend="pyarrow")
df

       ReferenceDate BondType MaturityDate  IndicativeRate       Price
0         2007-01-02      LFT   2007-01-10        -0.00015        <NA>
1         2007-01-02      LFT   2007-01-17       -0.000149        <NA>
2         2007-01-02      LFT   2007-02-14       -0.000154        <NA>
3         2007-01-02      LFT   2007-02-21        -0.00015        <NA>
4         2007-01-02      LFT   2007-03-14       -0.000148        <NA>
...              ...      ...          ...             ...         ...
233615    2025-08-25    NTN-F   2027-01-01        0.138871  970.334535
233616    2025-08-25    NTN-F   2029-01-01        0.133474  932.233659
233617    2025-08-25    NTN-F   2031-01-01        0.137845   883.29099
233618    2025-08-25    NTN-F   2033-01-01        0.138895  848.636792
233619    2025-08-25    NTN-F   2035-01-01        0.140215  819.743816

[233620 rows x 5 columns]

In [11]:
cols = ["ReferenceDate", "BondType", "MaturityDate", "IndicativeRate", "Price"]
df = df[cols].copy()
df

       ReferenceDate BondType MaturityDate  IndicativeRate       Price
0         2007-01-02      LFT   2007-01-10        -0.00015        <NA>
1         2007-01-02      LFT   2007-01-17       -0.000149        <NA>
2         2007-01-02      LFT   2007-02-14       -0.000154        <NA>
3         2007-01-02      LFT   2007-02-21        -0.00015        <NA>
4         2007-01-02      LFT   2007-03-14       -0.000148        <NA>
...              ...      ...          ...             ...         ...
233566    2025-08-22    NTN-F   2027-01-01        0.139268  969.400362
233567    2025-08-22    NTN-F   2029-01-01         0.13414  930.205447
233568    2025-08-22    NTN-F   2031-01-01         0.13841  881.036094
233569    2025-08-22    NTN-F   2033-01-01        0.139398  846.292149
233570    2025-08-22    NTN-F   2035-01-01        0.140633  817.568201

[233571 rows x 5 columns]

In [6]:
for col in ["ReferenceDate", "MaturityDate"]:
    df[col] = df[col].astype("date32[pyarrow]")
df

       ReferenceDate BondType MaturityDate  IndicativeRate       Price
0         2007-01-02      LFT   2007-01-10        -0.00015        <NA>
1         2007-01-02      LFT   2007-01-17       -0.000149        <NA>
2         2007-01-02      LFT   2007-02-14       -0.000154        <NA>
3         2007-01-02      LFT   2007-02-21        -0.00015        <NA>
4         2007-01-02      LFT   2007-03-14       -0.000148        <NA>
...              ...      ...          ...             ...         ...
233566    2025-08-22    NTN-F   2027-01-01        0.139268  969.400362
233567    2025-08-22    NTN-F   2029-01-01         0.13414  930.205447
233568    2025-08-22    NTN-F   2031-01-01         0.13841  881.036094
233569    2025-08-22    NTN-F   2033-01-01        0.139398  846.292149
233570    2025-08-22    NTN-F   2035-01-01        0.140633  817.568201

[233571 rows x 5 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233571 entries, 0 to 233570
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ReferenceDate   233571 non-null  date32[day][pyarrow]
 1   BondType        233571 non-null  string[pyarrow]
 2   MaturityDate    233571 non-null  date32[day][pyarrow]
 3   IndicativeRate  233571 non-null  double[pyarrow]
 4   Price           63764 non-null   double[pyarrow]
dtypes: date32[day][pyarrow](2), double[pyarrow](2), string[pyarrow](1)
memory usage: 7.2 MB

In [8]:
rdate = pd.to_datetime("03-01-2024", dayfirst=True)
df.query("ReferenceDate == @rdate").reset_index(drop=True)

   ReferenceDate BondType MaturityDate  IndicativeRate         Price
0     2024-01-03      LFT   2024-03-01        -0.00016  14282.392313
1     2024-01-03      LFT   2024-09-01       -0.000137  14283.334928
2     2024-01-03      LFT   2025-03-01        0.000014  14281.792468
3     2024-01-03      LFT   2025-09-01        0.000162  14278.193395
4     2024-01-03      LFT   2026-03-01        0.000411  14269.381379
5     2024-01-03      LFT   2026-09-01        0.000726  14254.499499
6     2024-01-03      LFT   2027-03-01        0.001206  14228.092015
7     2024-01-03      LFT   2027-09-01        0.001305  14214.195595
8     2024-01-03      LFT   2028-03-01        0.001374  14201.013276
9     2024-01-03      LFT   2028-09-01        0.001483  14183.931962
10    2024-01-03      LFT   2029-03-01        0.001606  14165.008266
11    2024-01-03      LFT   2029-09-01        0.001677  14147.727003
12    2024-01-03      LTN   2024-04-01        0.111034    975.242313
13    2024-01-03      LTN   2024-07-01        0.106105    951.969879
14    2024-01-03      LTN   2024-10-01        0.101534    930.039876
15    2024-01-03      LTN   2025-01-01        0.098623    910.230351
16    2024-01-03      LTN   2025-04-01        0.098665    889.698208
17    2024-01-03      LTN   2025-07-01        0.097795    870.685519
18    2024-01-03      LTN   2025-10-01        0.097528    850.027672
19    2024-01-03      LTN   2026-01-01         0.09715    830.745476
20    2024-01-03      LTN   2026-07-01        0.097955     792.83506
21    2024-01-03      LTN   2027-07-01        0.099889    718.229917
22    2024-01-03    NTN-B   2024-08-15        0.064763   4266.019173
23    2024-01-03    NTN-B   2025-05-15          0.0544   4247.937379
24    2024-01-03    NTN-B   2026-08-15        0.051766   4359.557528
25    2024-01-03    NTN-B   2027-05-15          0.0526   4311.562537
26    2024-01-03    NTN-B   2028-08-15         0.05227    4409.17578
27    2024-01-03    NTN-B   2030-08-15          0.0522   4461.454842
28    2024-01-03    NTN-B   2032-08-15        0.053212   4474.993178
29    2024-01-03    NTN-B   2033-05-15        0.053142   4429.449814
30    2024-01-03    NTN-B   2035-05-15         0.05348   4452.200578
31    2024-01-03    NTN-B   2040-08-15        0.053735   4570.338875
32    2024-01-03    NTN-B   2045-05-15        0.054804   4499.070163
33    2024-01-03    NTN-B   2050-08-15        0.054784   4594.344737
34    2024-01-03    NTN-B   2055-05-15          0.0548   4555.001564
35    2024-01-03    NTN-B   2060-08-15        0.054948   4625.061197
36    2024-01-03    NTN-C   2031-01-01        0.055269   8319.419694
37    2024-01-03    NTN-F   2025-01-01        0.098702   1001.206109
38    2024-01-03    NTN-F   2027-01-01        0.098851   1003.857578
39    2024-01-03    NTN-F   2029-01-01        0.101938      995.2765
40    2024-01-03    NTN-F   2031-01-01        0.103929    984.719625
41    2024-01-03    NTN-F   2033-01-01        0.104724    977.127029

In [9]:
df.to_parquet("../data/anbima_tpf.parquet", index=False, compression="gzip")