In [ ]:
import pandas as pd

di_file = "../data/b3_di.parquet"
df = pd.read_parquet(di_file)
df

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,DV01,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,1995-01-02,1995-02-01,DI1FEV5,22,185169,340,45045,2180001225,0.56255,<NA>,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,1995-01-02,1995-03-01,DI1MAR5,40,12145,21,1590,74621000,1.019868,<NA>,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,1995-01-02,1995-04-03,DI1ABR5,63,150,0,0,0,1.636827,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,1995-01-03,1995-02-01,DI1FEV5,21,193594,427,81175,3932939112,0.530598,<NA>,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,1995-01-03,1995-03-01,DI1MAR5,39,12295,96,13425,630682950,0.966267,<NA>,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217654,2025-04-11,2036-01-02,DI1F36,2684,22551,0,0,0,21.73562,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14615,23390.07
217655,2025-04-11,2037-01-02,DI1F37,2937,10459,1,2,40648,20.685502,0.1465,0.1465,0.1465,0.1465,0.1465,<NA>,<NA>,0.14639,20346.75
217656,2025-04-11,2038-01-04,DI1F38,3186,35427,0,0,0,19.821605,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14547,17958.8
217657,2025-04-11,2039-01-03,DI1F39,3437,8816,0,0,0,18.804642,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14494,15785.88
217658,2025-04-11,2040-01-02,DI1F40,3688,16316,0,0,0,17.700588,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14466,13844.39

In [14]:
df_last = pd.read_parquet("di1_last.parquet")
df_last["FinancialVolume"] = df_last["FinancialVolume"].round(0).astype("Int64")
df_last

,TradeDate,TickerSymbol,ExpirationDate,BDaysToExp,DaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,SettlementPrice,...,MinLimitRate,MaxLimitRate,BestBidRate,BestAskRate,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,DV01
0,2025-04-11,DI1K25,2025-05-02,12,21,1135215,1427,18906,1878713304,99371.2,...,0.13802,0.14522,0.14163,0.14159,0.1416,0.14157,0.14162,0.14165,0.14159,0.414488
1,2025-04-11,DI1M25,2025-06-02,33,52,807234,1520,14283,1403379220,98255.63,...,0.13918,0.14838,0.14385,0.14378,0.14384,0.1438,0.14386,0.14388,0.14385,1.124888
2,2025-04-11,DI1N25,2025-07-01,53,81,3445778,7754,205804,20002751697,97193.44,...,0.13917,0.15057,0.14492,0.14485,0.14509,0.14484,0.14495,0.14517,0.14489,1.785375
3,2025-04-11,DI1Q25,2025-08-01,76,112,361441,51,9911,951212957,95977.65,...,0.13965,0.1525,0.1459,0.1457,0.1459,0.1457,0.14591,0.146,0.1457,2.526172
4,2025-04-11,DI1U25,2025-09-01,97,143,738767,14,3412,323708420,94875.26,...,0.1398,0.15415,0.1465,0.14635,0.14655,0.14645,0.1465,0.1466,0.1465,3.185437
5,2025-04-11,DI1V25,2025-10-01,119,173,1985634,7717,130080,12192487297,93732.61,...,0.13965,0.1556,0.14685,0.1467,0.1473,0.1467,0.14694,0.14735,0.14675,3.859327
6,2025-04-11,DI1X25,2025-11-03,142,206,135202,220,4408,407992342,92560.07,...,0.13985,0.1563,0.1471,0.14685,0.14725,0.147,0.14712,0.14735,0.14705,4.547004
7,2025-04-11,DI1Z25,2025-12-01,161,234,309778,21,3499,320449400,91597.82,...,0.1398,0.15685,0.1472,0.147,0.14745,0.14725,0.14753,0.14755,0.14725,5.100966
8,2025-04-11,DI1F26,2026-01-02,183,266,4203634,22843,497431,45006232768,90490.43,...,0.14,0.1577,0.14745,0.14725,0.14795,0.14725,0.14774,0.1481,0.14725,5.726548
9,2025-04-11,DI1G26,2026-02-02,204,297,63307,18,773,69130901,89454.93,...,0.14,0.1584,0.14755,0.1472,0.148,0.1474,0.14794,0.14815,0.14745,6.310314
10,2025-04-11,DI1H26,2026-03-02,222,325,57486,31,991,87782530,88584.43,...,0.1398,0.1588,0.1475,0.1471,0.1479,0.14725,0.14757,0.1481,0.1473,6.800696
11,2025-04-11,DI1J26,2026-04-01,244,355,1126384,5677,99729,8728459388,87541.47,...,0.1395,0.15905,0.1472,0.1469,0.14815,0.14695,0.14757,0.1483,0.1471,7.387923
12,2025-04-11,DI1N26,2026-07-01,305,446,2152962,21246,157849,13375265945,84775.72,...,0.1386,0.15855,0.14605,0.1458,0.14745,0.14575,0.14667,0.1476,0.1459,8.951722
13,2025-04-11,DI1V26,2026-10-01,370,538,467139,4374,40158,3289500138,82001.19,...,0.1372,0.15755,0.1455,0.1439,0.14625,0.14415,0.14554,0.14635,0.14435,10.517823
14,2025-04-11,DI1F27,2027-01-04,432,633,3228808,61566,598061,47465738459,79453.77,...,0.1361,0.15695,0.14315,0.1431,0.14505,0.143,0.14431,0.1456,0.1431,11.910532
15,2025-04-11,DI1J27,2027-04-01,492,720,448300,6310,51136,3934643448,77029.45,...,0.1355,0.15685,0.14275,0.14115,0.14475,0.1424,0.14366,0.1451,0.1427,13.157323
16,2025-04-11,DI1N27,2027-07-01,555,811,1012169,15343,61413,4573236106,74592.61,...,0.13485,0.1564,0.14205,0.14175,0.1441,0.14165,0.14323,0.14465,0.14205,14.380873
17,2025-04-11,DI1V27,2027-10-01,620,903,136162,1176,10115,727878882,72115.65,...,0.13445,0.1562,<NA>,0.1415,0.14385,0.1414,0.1431,0.14435,0.1418,15.535189
18,2025-04-11,DI1F28,2028-01-03,683,997,1335972,38999,197139,13723311236,69794.3,...,0.13425,0.1561,0.14155,0.14145,0.1435,0.1411,0.14299,0.14435,0.14145,16.565931
19,2025-04-11,DI1J28,2028-04-03,746,1088,129461,299,4691,315939424,67522.37,...,0.1341,0.15615,<NA>,<NA>,0.1437,0.14145,0.14284,0.1443,0.14155,17.505443
20,2025-04-11,DI1N28,2028-07-03,807,1179,340311,5784,26930,1755265937,65346.38,...,0.13435,0.15655,0.14185,0.14145,0.14405,0.1413,0.143,0.1446,0.14165,18.322899
21,2025-04-11,DI1V28,2028-10-02,871,1270,60843,146,876,55168597,63098.0,...,0.1348,0.15695,<NA>,<NA>,0.1437,0.1421,0.14314,0.1448,0.1421,19.088561
22,2025-04-11,DI1F29,2029-01-02,931,1362,1881208,48036,343425,20921869483,61100.23,...,0.13485,0.1571,0.14225,0.1422,0.1442,0.14175,0.14355,0.1452,0.14225,19.755079
23,2025-04-11,DI1J29,2029-04-02,992,1452,70528,93,2574,151661437,59094.28,...,0.13495,0.15725,<NA>,<NA>,0.1442,0.14225,0.14382,0.14525,0.14225,20.352687
24,2025-04-11,DI1N29,2029-07-02,1055,1543,87183,312,1766,100353788,57056.5,...,0.13555,0.158,<NA>,<NA>,0.14525,0.1426,0.14453,0.1459,0.1431,20.890434
25,2025-04-11,DI1V29,2029-10-01,1119,1634,62212,88,651,35829482,55067.81,...,0.136,0.1585,<NA>,<NA>,0.14565,0.143,0.14394,0.14565,0.1431,21.378501
26,2025-04-11,DI1F30,2030-01-02,1180,1727,975413,18913,62948,3338563925,53220.64,...,0.1364,0.1589,0.1439,0.14375,0.146,0.14325,0.14503,0.14665,0.14385,21.780278
27,2025-04-11,DI1J30,2030-04-01,1241,1816,18457,66,495,25352134,51460.18,...,0.1367,0.1594,<NA>,<NA>,0.1456,0.14425,0.14553,0.1465,0.1443,22.143859
28,2025-04-11,DI1N30,2030-07-01,1303,1907,34755,109,620,30651137,49692.56,...,0.137,0.1596,<NA>,<NA>,0.146,0.1451,0.14596,0.1471,0.1451,22.443885
29,2025-04-11,DI1F31,2031-01-02,1432,2092,1165219,28837,139298,6414718600,46242.16,...,0.1376,0.1602,0.1451,0.1449,0.1472,0.1444,0.1462,0.1478,0.145,22.942185
30,2025-04-11,DI1F32,2032-01-02,1684,2457,430315,3452,29717,1188762366,40220.35,...,0.1385,0.1612,0.1459,0.1455,0.1481,0.1452,0.14695,0.1485,0.1456,23.452827
31,2025-04-11,DI1F33,2033-01-03,1936,2824,393544,12798,44825,1560357226,35034.56,...,0.1389,0.1617,0.1461,0.1458,0.1485,0.1454,0.14724,0.1489,0.1459,23.480685
32,2025-04-11,DI1F34,2034-01-02,2187,3188,90711,136,265,8065240,30619.66,...,0.1389,0.1617,<NA>,<NA>,0.1482,0.1454,0.14691,0.1485,0.1454,23.185812
33,2025-04-11,DI1F35,2035-01-02,2435,3553,481620,13157,97663,2593165660,26753.75,...,0.1393,0.1621,0.1459,0.1457,0.1485,0.1452,0.1471,0.149,0.1458,22.553954
34,2025-04-11,DI1F36,2036-01-02,2684,3918,22551,0,0,0,23390.07,...,0.1392,0.162,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,21.73562
35,2025-04-11,DI1F37,2037-01-02,2937,4284,10459,1,2,40648,20346.75,...,0.1395,0.1623,<NA>,<NA>,0.1465,0.1465,0.1465,0.1465,0.1465,20.685502
36,2025-04-11,DI1F38,2038-01-04,3186,4651,35427,0,0,0,17958.8,...,0.1386,0.1614,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,19.821605
37,2025-04-11,DI1F39,2039-01-03,3437,5015,8816,0,0,0,15785.88,...,0.138,0.1608,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18.804642
38,2025-04-11,DI1F40,2040-01-02,3688,5379,16316,0,0,0,13844.39,...,0.1377,0.1606,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17.700588

In [16]:
columns = [c for c in df_last.columns if c in df.columns]
df_last = df_last[columns].copy()
df_last

,TradeDate,TickerSymbol,ExpirationDate,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,SettlementPrice,SettlementRate,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,DV01
0,2025-04-11,DI1K25,2025-05-02,12,1135215,1427,18906,1878713304,99371.2,0.14164,0.1416,0.14157,0.14162,0.14165,0.14159,0.414488
1,2025-04-11,DI1M25,2025-06-02,33,807234,1520,14283,1403379220,98255.63,0.14383,0.14384,0.1438,0.14386,0.14388,0.14385,1.124888
2,2025-04-11,DI1N25,2025-07-01,53,3445778,7754,205804,20002751697,97193.44,0.14494,0.14509,0.14484,0.14495,0.14517,0.14489,1.785375
3,2025-04-11,DI1Q25,2025-08-01,76,361441,51,9911,951212957,95977.65,0.14583,0.1459,0.1457,0.14591,0.146,0.1457,2.526172
4,2025-04-11,DI1U25,2025-09-01,97,738767,14,3412,323708420,94875.26,0.14645,0.14655,0.14645,0.1465,0.1466,0.1465,3.185437
5,2025-04-11,DI1V25,2025-10-01,119,1985634,7717,130080,12192487297,93732.61,0.1469,0.1473,0.1467,0.14694,0.14735,0.14675,3.859327
6,2025-04-11,DI1X25,2025-11-03,142,135202,220,4408,407992342,92560.07,0.14706,0.14725,0.147,0.14712,0.14735,0.14705,4.547004
7,2025-04-11,DI1Z25,2025-12-01,161,309778,21,3499,320449400,91597.82,0.14725,0.14745,0.14725,0.14753,0.14755,0.14725,5.100966
8,2025-04-11,DI1F26,2026-01-02,183,4203634,22843,497431,45006232768,90490.43,0.14752,0.14795,0.14725,0.14774,0.1481,0.14725,5.726548
9,2025-04-11,DI1G26,2026-02-02,204,63307,18,773,69130901,89454.93,0.14758,0.148,0.1474,0.14794,0.14815,0.14745,6.310314
10,2025-04-11,DI1H26,2026-03-02,222,57486,31,991,87782530,88584.43,0.14751,0.1479,0.14725,0.14757,0.1481,0.1473,6.800696
11,2025-04-11,DI1J26,2026-04-01,244,1126384,5677,99729,8728459388,87541.47,0.14731,0.14815,0.14695,0.14757,0.1483,0.1471,7.387923
12,2025-04-11,DI1N26,2026-07-01,305,2152962,21246,157849,13375265945,84775.72,0.14621,0.14745,0.14575,0.14667,0.1476,0.1459,8.951722
13,2025-04-11,DI1V26,2026-10-01,370,467139,4374,40158,3289500138,82001.19,0.14471,0.14625,0.14415,0.14554,0.14635,0.14435,10.517823
14,2025-04-11,DI1F27,2027-01-04,432,3228808,61566,598061,47465738459,79453.77,0.14358,0.14505,0.143,0.14431,0.1456,0.1431,11.910532
15,2025-04-11,DI1J27,2027-04-01,492,448300,6310,51136,3934643448,77029.45,0.14302,0.14475,0.1424,0.14366,0.1451,0.1427,13.157323
16,2025-04-11,DI1N27,2027-07-01,555,1012169,15343,61413,4573236106,74592.61,0.14236,0.1441,0.14165,0.14323,0.14465,0.14205,14.380873
17,2025-04-11,DI1V27,2027-10-01,620,136162,1176,10115,727878882,72115.65,0.1421,0.14385,0.1414,0.1431,0.14435,0.1418,15.535189
18,2025-04-11,DI1F28,2028-01-03,683,1335972,38999,197139,13723311236,69794.3,0.14189,0.1435,0.1411,0.14299,0.14435,0.14145,16.565931
19,2025-04-11,DI1J28,2028-04-03,746,129461,299,4691,315939424,67522.37,0.14186,0.1437,0.14145,0.14284,0.1443,0.14155,17.505443
20,2025-04-11,DI1N28,2028-07-03,807,340311,5784,26930,1755265937,65346.38,0.14209,0.14405,0.1413,0.143,0.1446,0.14165,18.322899
21,2025-04-11,DI1V28,2028-10-02,871,60843,146,876,55168597,63098.0,0.14251,0.1437,0.1421,0.14314,0.1448,0.1421,19.088561
22,2025-04-11,DI1F29,2029-01-02,931,1881208,48036,343425,20921869483,61100.23,0.14265,0.1442,0.14175,0.14355,0.1452,0.14225,19.755079
23,2025-04-11,DI1J29,2029-04-02,992,70528,93,2574,151661437,59094.28,0.14297,0.1442,0.14225,0.14382,0.14525,0.14225,20.352687
24,2025-04-11,DI1N29,2029-07-02,1055,87183,312,1766,100353788,57056.5,0.14343,0.14525,0.1426,0.14453,0.1459,0.1431,20.890434
25,2025-04-11,DI1V29,2029-10-01,1119,62212,88,651,35829482,55067.81,0.1438,0.14565,0.143,0.14394,0.14565,0.1431,21.378501
26,2025-04-11,DI1F30,2030-01-02,1180,975413,18913,62948,3338563925,53220.64,0.14419,0.146,0.14325,0.14503,0.14665,0.14385,21.780278
27,2025-04-11,DI1J30,2030-04-01,1241,18457,66,495,25352134,51460.18,0.14443,0.1456,0.14425,0.14553,0.1465,0.1443,22.143859
28,2025-04-11,DI1N30,2030-07-01,1303,34755,109,620,30651137,49692.56,0.14482,0.146,0.1451,0.14596,0.1471,0.1451,22.443885
29,2025-04-11,DI1F31,2031-01-02,1432,1165219,28837,139298,6414718600,46242.16,0.14537,0.1472,0.1444,0.1462,0.1478,0.145,22.942185
30,2025-04-11,DI1F32,2032-01-02,1684,430315,3452,29717,1188762366,40220.35,0.14602,0.1481,0.1452,0.14695,0.1485,0.1456,23.452827
31,2025-04-11,DI1F33,2033-01-03,1936,393544,12798,44825,1560357226,35034.56,0.14628,0.1485,0.1454,0.14724,0.1489,0.1459,23.480685
32,2025-04-11,DI1F34,2034-01-02,2187,90711,136,265,8065240,30619.66,0.14611,0.1482,0.1454,0.14691,0.1485,0.1454,23.185812
33,2025-04-11,DI1F35,2035-01-02,2435,481620,13157,97663,2593165660,26753.75,0.1462,0.1485,0.1452,0.1471,0.149,0.1458,22.553954
34,2025-04-11,DI1F36,2036-01-02,2684,22551,0,0,0,23390.07,0.14615,<NA>,<NA>,<NA>,<NA>,<NA>,21.73562
35,2025-04-11,DI1F37,2037-01-02,2937,10459,1,2,40648,20346.75,0.14639,0.1465,0.1465,0.1465,0.1465,0.1465,20.685502
36,2025-04-11,DI1F38,2038-01-04,3186,35427,0,0,0,17958.8,0.14547,<NA>,<NA>,<NA>,<NA>,<NA>,19.821605
37,2025-04-11,DI1F39,2039-01-03,3437,8816,0,0,0,15785.88,0.14494,<NA>,<NA>,<NA>,<NA>,<NA>,18.804642
38,2025-04-11,DI1F40,2040-01-02,3688,16316,0,0,0,13844.39,0.14466,<NA>,<NA>,<NA>,<NA>,<NA>,17.700588

In [17]:
df = pd.concat([df, df_last], ignore_index=True)
df.tail(50)

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,DV01,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
217609,2025-04-10,2030-07-01,DI1N30,1304,35593,17,82,4042488,22.216779,0.1463,0.1463,0.14646,0.1473,0.1468,<NA>,<NA>,0.14675,49234.87
217610,2025-04-10,2031-01-02,DI1F31,1433,1164228,28921,174964,8014345619,22.677083,0.1466,0.1454,0.14717,0.1482,0.1479,0.1479,0.1477,0.14739,45756.48
217611,2025-04-10,2032-01-02,DI1F32,1685,428943,2133,16744,665456858,23.103114,0.1473,0.1462,0.14797,0.1488,0.1485,0.1489,0.1484,0.14827,39674.84
217612,2025-04-10,2033-01-03,DI1F33,1937,388735,10924,40290,1393367950,23.059096,0.1473,0.1465,0.14813,0.1492,0.149,0.1493,0.1488,0.14867,34459.46
217613,2025-04-10,2034-01-02,DI1F34,2188,90566,105,424,12759238,22.692212,0.1483,0.1476,0.14833,0.149,0.1489,<NA>,<NA>,0.14865,30020.49
217614,2025-04-10,2035-01-02,DI1F35,2436,482579,9605,77650,2037200661,21.967593,0.1474,0.1466,0.14845,0.1494,0.1493,0.1495,0.1492,0.14902,26111.59
217615,2025-04-10,2036-01-02,DI1F36,2685,22551,1,2,45830,21.118364,0.1483,0.1483,0.1483,0.1483,0.1483,<NA>,<NA>,0.14897,22773.26
217616,2025-04-10,2037-01-02,DI1F37,2938,10459,0,0,0,20.043606,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14923,19757.48
217617,2025-04-10,2038-01-04,DI1F38,3187,35427,0,0,0,19.158645,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14831,17395.72
217618,2025-04-10,2039-01-03,DI1F39,3438,8816,0,0,0,18.130244,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14778,15253.06
217619,2025-04-10,2040-01-02,DI1F40,3689,16316,0,0,0,17.023248,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.1475,13344.03
217620,2025-04-11,2025-05-02,DI1K25,12,1135215,1427,18906,1878713304,0.414488,0.1416,0.14157,0.14162,0.14165,0.14159,<NA>,<NA>,0.14164,99371.2
217621,2025-04-11,2025-06-02,DI1M25,33,807234,1520,14283,1403379220,1.124888,0.14384,0.1438,0.14386,0.14388,0.14385,<NA>,<NA>,0.14383,98255.63
217622,2025-04-11,2025-07-01,DI1N25,53,3445778,7754,205804,20002751697,1.785375,0.14509,0.14484,0.14495,0.14517,0.14489,<NA>,<NA>,0.14494,97193.44
217623,2025-04-11,2025-08-01,DI1Q25,76,361441,51,9911,951212957,2.526172,0.1459,0.1457,0.14591,0.146,0.1457,<NA>,<NA>,0.14583,95977.65
217624,2025-04-11,2025-09-01,DI1U25,97,738767,14,3412,323708420,3.185437,0.14655,0.14645,0.1465,0.1466,0.1465,<NA>,<NA>,0.14645,94875.26
217625,2025-04-11,2025-10-01,DI1V25,119,1985634,7717,130080,12192487297,3.859327,0.1473,0.1467,0.14694,0.14735,0.14675,<NA>,<NA>,0.1469,93732.61
217626,2025-04-11,2025-11-03,DI1X25,142,135202,220,4408,407992342,4.547004,0.14725,0.147,0.14712,0.14735,0.14705,<NA>,<NA>,0.14706,92560.07
217627,2025-04-11,2025-12-01,DI1Z25,161,309778,21,3499,320449400,5.100966,0.14745,0.14725,0.14753,0.14755,0.14725,<NA>,<NA>,0.14725,91597.82
217628,2025-04-11,2026-01-02,DI1F26,183,4203634,22843,497431,45006232768,5.726548,0.14795,0.14725,0.14774,0.1481,0.14725,<NA>,<NA>,0.14752,90490.43
217629,2025-04-11,2026-02-02,DI1G26,204,63307,18,773,69130901,6.310314,0.148,0.1474,0.14794,0.14815,0.14745,<NA>,<NA>,0.14758,89454.93
217630,2025-04-11,2026-03-02,DI1H26,222,57486,31,991,87782530,6.800696,0.1479,0.14725,0.14757,0.1481,0.1473,<NA>,<NA>,0.14751,88584.43
217631,2025-04-11,2026-04-01,DI1J26,244,1126384,5677,99729,8728459388,7.387923,0.14815,0.14695,0.14757,0.1483,0.1471,<NA>,<NA>,0.14731,87541.47
217632,2025-04-11,2026-07-01,DI1N26,305,2152962,21246,157849,13375265945,8.951722,0.14745,0.14575,0.14667,0.1476,0.1459,<NA>,<NA>,0.14621,84775.72
217633,2025-04-11,2026-10-01,DI1V26,370,467139,4374,40158,3289500138,10.517823,0.14625,0.14415,0.14554,0.14635,0.14435,<NA>,<NA>,0.14471,82001.19
217634,2025-04-11,2027-01-04,DI1F27,432,3228808,61566,598061,47465738459,11.910532,0.14505,0.143,0.14431,0.1456,0.1431,<NA>,<NA>,0.14358,79453.77
217635,2025-04-11,2027-04-01,DI1J27,492,448300,6310,51136,3934643448,13.157323,0.14475,0.1424,0.14366,0.1451,0.1427,<NA>,<NA>,0.14302,77029.45
217636,2025-04-11,2027-07-01,DI1N27,555,1012169,15343,61413,4573236106,14.380873,0.1441,0.14165,0.14323,0.14465,0.14205,<NA>,<NA>,0.14236,74592.61
217637,2025-04-11,2027-10-01,DI1V27,620,136162,1176,10115,727878882,15.535189,0.14385,0.1414,0.1431,0.14435,0.1418,<NA>,<NA>,0.1421,72115.65
217638,2025-04-11,2028-01-03,DI1F28,683,1335972,38999,197139,13723311236,16.565931,0.1435,0.1411,0.14299,0.14435,0.14145,<NA>,<NA>,0.14189,69794.3
217639,2025-04-11,2028-04-03,DI1J28,746,129461,299,4691,315939424,17.505443,0.1437,0.14145,0.14284,0.1443,0.14155,<NA>,<NA>,0.14186,67522.37
217640,2025-04-11,2028-07-03,DI1N28,807,340311,5784,26930,1755265937,18.322899,0.14405,0.1413,0.143,0.1446,0.14165,<NA>,<NA>,0.14209,65346.38
217641,2025-04-11,2028-10-02,DI1V28,871,60843,146,876,55168597,19.088561,0.1437,0.1421,0.14314,0.1448,0.1421,<NA>,<NA>,0.14251,63098.0
217642,2025-04-11,2029-01-02,DI1F29,931,1881208,48036,343425,20921869483,19.755079,0.1442,0.14175,0.14355,0.1452,0.14225,<NA>,<NA>,0.14265,61100.23
217643,2025-04-11,2029-04-02,DI1J29,992,70528,93,2574,151661437,20.352687,0.1442,0.14225,0.14382,0.14525,0.14225,<NA>,<NA>,0.14297,59094.28
217644,2025-04-11,2029-07-02,DI1N29,1055,87183,312,1766,100353788,20.890434,0.14525,0.1426,0.14453,0.1459,0.1431,<NA>,<NA>,0.14343,57056.5
217645,2025-04-11,2029-10-01,DI1V29,1119,62212,88,651,35829482,21.378501,0.14565,0.143,0.14394,0.14565,0.1431,<NA>,<NA>,0.1438,55067.81
217646,2025-04-11,2030-01-02,DI1F30,1180,975413,18913,62948,3338563925,21.780278,0.146,0.14325,0.14503,0.14665,0.14385,<NA>,<NA>,0.14419,53220.64
217647,2025-04-11,2030-04-01,DI1J30,1241,18457,66,495,25352134,22.143859,0.1456,0.14425,0.14553,0.1465,0.1443,<NA>,<NA>,0.14443,51460.18
217648,2025-04-11,2030-07-01,DI1N30,1303,34755,109,620,30651137,22.443885,0.146,0.1451,0.14596,0.1471,0.1451,<NA>,<NA>,0.14482,49692.56
217649,2025-04-11,2031-01-02,DI1F31,1432,1165219,28837,139298,6414718600,22.942185,0.1472,0.1444,0.1462,0.1478,0.145,<NA>,<NA>,0.14537,46242.16
217650,2025-04-11,2032-01-02,DI1F32,1684,430315,3452,29717,1188762366,23.452827,0.1481,0.1452,0.14695,0.1485,0.1456,<NA>,<NA>,0.14602,40220.35
217651,2025-04-11,2033-01-03,DI1F33,1936,393544,12798,44825,1560357226,23.480685,0.1485,0.1454,0.14724,0.1489,0.1459,<NA>,<NA>,0.14628,35034.56
217652,2025-04-11,2034-01-02,DI1F34,2187,90711,136,265,8065240,23.185812,0.1482,0.1454,0.14691,0.1485,0.1454,<NA>,<NA>,0.14611,30619.66
217653,2025-04-11,2035-01-02,DI1F35,2435,481620,13157,97663,2593165660,22.553954,0.1485,0.1452,0.1471,0.149,0.1458,<NA>,<NA>,0.1462,26753.75
217654,2025-04-11,2036-01-02,DI1F36,2684,22551,0,0,0,21.73562,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14615,23390.07
217655,2025-04-11,2037-01-02,DI1F37,2937,10459,1,2,40648,20.685502,0.1465,0.1465,0.1465,0.1465,0.1465,<NA>,<NA>,0.14639,20346.75
217656,2025-04-11,2038-01-04,DI1F38,3186,35427,0,0,0,19.821605,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14547,17958.8
217657,2025-04-11,2039-01-03,DI1F39,3437,8816,0,0,0,18.804642,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14494,15785.88
217658,2025-04-11,2040-01-02,DI1F40,3688,16316,0,0,0,17.700588,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14466,13844.39

In [ ]:
#  df.to_parquet(di_file, compression="gzip", index=False)