In [3]:
import pandas as pd

In [4]:
df = pd.read_parquet("../anbima_data.parquet")
df

       BondType ReferenceDate MaturityDate  IndicativeRate
0           LFT    2007-01-02   2007-01-10        -0.00015
1           LFT    2007-01-02   2007-01-17       -0.000149
2           LFT    2007-01-02   2007-02-14       -0.000154
3           LFT    2007-01-02   2007-02-21        -0.00015
4           LFT    2007-01-02   2007-03-14       -0.000148
...         ...           ...          ...             ...
220759    NTN-F    2024-12-27   2027-01-01        0.157464
220760    NTN-F    2024-12-27   2029-01-01        0.156888
220761    NTN-F    2024-12-27   2031-01-01        0.154971
220762    NTN-F    2024-12-27   2033-01-01        0.152634
220763    NTN-F    2024-12-27   2035-01-01        0.150856

[220764 rows x 4 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220764 entries, 0 to 220763
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   BondType        220764 non-null  string
 1   ReferenceDate   220764 non-null  datetime64[ns]
 2   MaturityDate    220764 non-null  datetime64[ns]
 3   IndicativeRate  220764 non-null  Float64
dtypes: Float64(1), datetime64[ns](2), string(1)
memory usage: 6.9 MB

In [9]:
rdate = pd.Timestamp("2024-11-22")

df.query("ReferenceDate == @rdate")

       BondType ReferenceDate MaturityDate  IndicativeRate
219589      LFT    2024-11-22   2025-03-01       -0.000232
219590      LFT    2024-11-22   2025-09-01       -0.000228
219591      LFT    2024-11-22   2026-03-01       -0.000009
219592      LFT    2024-11-22   2026-09-01        0.000006
219593      LFT    2024-11-22   2027-03-01        0.000383
219594      LFT    2024-11-22   2027-09-01        0.000518
219595      LFT    2024-11-22   2028-03-01        0.000742
219596      LFT    2024-11-22   2028-09-01        0.000984
219597      LFT    2024-11-22   2029-03-01        0.001142
219598      LFT    2024-11-22   2029-09-01        0.001232
219599      LFT    2024-11-22   2030-03-01        0.001258
219600      LFT    2024-11-22   2030-06-01        0.001257
219601      LFT    2024-11-22   2030-09-01        0.001257
219602      LFT    2024-11-22   2030-12-01        0.001258
219603      LTN    2024-11-22   2025-01-01        0.114599
219604      LTN    2024-11-22   2025-04-01        0.120323
219605      LTN    2024-11-22   2025-07-01        0.125451
219606      LTN    2024-11-22   2025-10-01         0.12943
219607      LTN    2024-11-22   2026-01-01        0.131933
219608      LTN    2024-11-22   2026-04-01        0.133473
219609      LTN    2024-11-22   2026-07-01        0.133995
219610      LTN    2024-11-22   2026-10-01        0.134082
219611      LTN    2024-11-22   2027-07-01        0.133711
219612      LTN    2024-11-22   2028-01-01        0.133351
219613      LTN    2024-11-22   2028-07-01        0.133276
219614      LTN    2024-11-22   2030-01-01        0.132405
219615    NTN-B    2024-11-22   2025-05-15        0.045621
219616    NTN-B    2024-11-22   2026-08-15         0.06992
219617    NTN-B    2024-11-22   2027-05-15          0.0699
219618    NTN-B    2024-11-22   2028-08-15        0.070493
219619    NTN-B    2024-11-22   2029-05-15         0.06924
219620    NTN-B    2024-11-22   2030-08-15        0.068967
219621    NTN-B    2024-11-22   2032-08-15        0.068636
219622    NTN-B    2024-11-22   2033-05-15        0.068411
219623    NTN-B    2024-11-22   2035-05-15        0.067572
219624    NTN-B    2024-11-22   2040-08-15        0.066494
219625    NTN-B    2024-11-22   2045-05-15        0.067029
219626    NTN-B    2024-11-22   2050-08-15        0.066736
219627    NTN-B    2024-11-22   2055-05-15        0.066553
219628    NTN-B    2024-11-22   2060-08-15        0.066536
219629    NTN-C    2024-11-22   2031-01-01        0.064706
219630    NTN-F    2024-11-22   2025-01-01         0.11481
219631    NTN-F    2024-11-22   2027-01-01         0.13353
219632    NTN-F    2024-11-22   2029-01-01        0.132159
219633    NTN-F    2024-11-22   2031-01-01        0.131194
219634    NTN-F    2024-11-22   2033-01-01        0.129725
219635    NTN-F    2024-11-22   2035-01-01         0.12893

In [5]:
# df.to_parquet("../anbima_data.parquet", index=False, compression="gzip")

In [5]:
df = pd.read_parquet("../di_data.parquet")
df

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,DV01,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,1995-01-02,1995-02-01,DI1FEV5,22,185169,340,45045,2180001225,0.56255,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,1995-01-02,1995-03-01,DI1MAR5,40,12145,21,1590,74621000,1.019868,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,1995-01-02,1995-04-03,DI1ABR5,63,150,0,0,0,1.636827,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,1995-01-03,1995-02-01,DI1FEV5,21,193594,427,81175,3932939112,0.530598,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,1995-01-03,1995-03-01,DI1MAR5,39,12295,96,13425,630682950,0.966267,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214695,2024-12-18,2035-01-02,DI1F35,2513,297182,9619,24981,641850479,21.826282,0.1421,0.1408,0.14601,0.1492,0.1475,0.1481,0.1467,0.14851,25137.53
214696,2024-12-18,2036-01-02,DI1F36,2762,21985,0,0,0,20.965083,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14831,21965.07
214697,2024-12-18,2037-01-02,DI1F37,3015,4618,30,31,613189,20.070067,0.144,0.144,0.14504,0.1465,0.1465,0.1472,0.1452,0.14764,19251.64
214698,2024-12-18,2038-01-04,DI1F38,3264,3522,0,0,0,18.963482,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14764,16802.51
214699,2024-12-18,2039-01-03,DI1F39,3515,4141,0,0,0,17.804292,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14764,14648.92

In [6]:
df.query("TradeDate == TradeDate.max()")

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,DV01,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
214624,2024-12-17,2025-01-02,DI1F25,10,6676790,4785,645524,64259107758,0.352186,0.12152,0.12151,0.1216,0.12176,0.12159,0.12165,0.12159,0.12163,99545.55
214625,2024-12-17,2025-02-03,DI1G25,32,925662,1643,1005566,99090911430,1.11457,0.12252,0.1224,0.12257,0.1228,0.1228,0.1228,0.12277,0.12269,98541.19
214626,2024-12-17,2025-03-05,DI1H25,52,957688,1144,147186,14359379011,1.785921,0.12698,0.12672,0.1272,0.12759,0.12749,0.12754,0.12744,0.12722,97559.16
214627,2024-12-17,2025-04-01,DI1J25,71,3307410,13488,623070,60188525838,2.407131,0.1302,0.1299,0.13063,0.13135,0.13085,0.1309,0.13085,0.13066,96599.29
214628,2024-12-17,2025-05-02,DI1K25,91,274618,144,12171,1162969402,3.042265,0.13375,0.13375,0.13426,0.1353,0.1348,0.13465,0.1343,0.13421,95554.16
214629,2024-12-17,2025-06-02,DI1M25,112,222137,531,13373,1262822830,3.689672,0.1372,0.1372,0.13761,0.1389,0.138,0.138,0.1379,0.13752,94434.2
214630,2024-12-17,2025-07-01,DI1N25,132,2079643,49077,497073,46397096219,4.288319,0.14015,0.13915,0.14061,0.14215,0.14075,0.14095,0.1406,0.1403,93353.98
214631,2024-12-17,2025-08-01,DI1Q25,155,102120,47,3974,366045222,4.95931,0.1427,0.14245,0.14295,0.1445,0.143,0.14345,0.1427,0.14261,92127.25
214632,2024-12-17,2025-09-01,DI1U25,176,149502,63,2350,213675482,5.55092,0.1447,0.1447,0.14591,0.14625,0.1451,0.14555,0.1449,0.1448,90987.66
214633,2024-12-17,2025-10-01,DI1V25,198,1017385,28701,242095,21730843598,6.152575,0.1471,0.14565,0.14736,0.1495,0.14735,0.14735,0.1471,0.14677,89798.4
214634,2024-12-17,2025-11-03,DI1X25,221,64930,8,1136,100612522,6.766231,0.148,0.148,0.14847,0.14915,0.149,0.1492,0.1484,0.14819,88586.77
214635,2024-12-17,2025-12-01,DI1Z25,240,62506,121,4259,372687091,7.257339,0.14905,0.14905,0.15043,0.1521,0.15015,0.15025,0.1497,0.14936,87583.6
214636,2024-12-17,2026-01-02,DI1F26,262,3330822,150139,1138325,98297335999,7.808316,0.151,0.14945,0.15157,0.15405,0.15115,0.15115,0.1511,0.1507,86420.89
214637,2024-12-17,2026-04-01,DI1J26,323,725666,33444,147477,12272776776,9.261843,0.1531,0.1521,0.1541,0.1568,0.1535,0.1535,0.15335,0.15303,83317.46
214638,2024-12-17,2026-07-01,DI1N26,384,2107879,116080,486291,39030854394,10.614904,0.1544,0.15305,0.15521,0.1582,0.1543,0.1546,0.1543,0.15402,80389.39
214639,2024-12-17,2026-10-01,DI1V26,449,372666,14607,72444,5597564535,11.957421,0.15485,0.15295,0.15574,0.15875,0.1543,0.15465,0.15275,0.15416,77456.48
214640,2024-12-17,2027-01-04,DI1F27,511,2493713,222029,1035808,77231769482,13.139651,0.1553,0.15265,0.15576,0.159,0.1541,0.15425,0.154,0.15408,74782.4
214641,2024-12-17,2027-04-01,DI1J27,571,133025,1989,18179,1310157095,14.193567,0.15575,0.15255,0.15552,0.15905,0.1541,<NA>,0.1538,0.15399,72286.64
214642,2024-12-17,2027-07-01,DI1N27,634,779308,47162,133727,9299555316,15.208054,0.1551,0.1521,0.15532,0.15915,0.15365,0.155,0.15355,0.15393,69753.24
214643,2024-12-17,2027-10-01,DI1V27,699,116544,860,3296,220806651,16.183128,0.15565,0.15235,0.15537,0.15855,0.15365,0.1541,0.15305,0.15348,67297.03
214644,2024-12-17,2028-01-03,DI1F28,762,1059200,97707,322501,20884734122,17.052194,0.15455,0.15085,0.15453,0.15825,0.15255,0.1529,0.1525,0.15299,65020.66
214645,2024-12-17,2028-04-03,DI1J28,825,97539,266,1035,64774062,17.850238,0.15445,0.15155,0.15391,0.15715,0.15275,0.15235,0.15165,0.15248,62838.24
214646,2024-12-17,2028-07-03,DI1N28,886,249431,13063,48828,2954434933,18.551772,0.15375,0.14975,0.15361,0.1573,0.1519,0.152,<NA>,0.15208,60790.38
214647,2024-12-17,2028-10-02,DI1V28,950,47187,252,1793,104599042,19.221974,0.15395,0.14975,0.15368,0.1564,0.1518,0.1515,0.15095,0.15167,58722.29
214648,2024-12-17,2029-01-02,DI1F29,1010,1208700,137331,578897,32724441755,19.805056,0.1527,0.14855,0.15295,0.1564,0.1505,0.1508,0.15035,0.15115,56883.61
214649,2024-12-17,2029-04-02,DI1J29,1071,50789,29,422,23091417,20.35424,0.1513,0.14955,0.15243,0.1551,0.1503,0.1503,0.1497,0.15054,55102.04
214650,2024-12-17,2029-07-02,DI1N29,1134,68548,564,2450,129976280,20.848924,0.1519,0.1478,0.15128,0.1553,0.14945,0.14985,0.14925,0.15014,53287.07
214651,2024-12-17,2029-10-01,DI1V29,1198,48918,30,168,8586446,21.31222,0.1518,0.1495,0.15164,0.15415,0.1495,0.1494,0.14745,0.14962,51537.9
214652,2024-12-17,2030-01-02,DI1F30,1259,892413,39382,181296,8974102591,21.671022,0.1513,0.1465,0.15114,0.1546,0.1488,0.1491,0.1486,0.14947,49859.95
214653,2024-12-17,2031-01-02,DI1F31,1511,784739,67214,289629,12564730332,22.841276,0.1499,0.1447,0.14945,0.1527,0.1471,0.1474,0.1471,0.14792,43728.85
214654,2024-12-17,2032-01-02,DI1F32,1763,140818,1019,3676,140567496,23.45559,0.1488,0.1436,0.1473,0.151,0.1457,0.1461,0.1454,0.14645,38437.02
214655,2024-12-17,2033-01-03,DI1F33,2015,475886,27011,88744,2965035904,23.577292,0.1473,0.142,0.14695,0.1501,0.1445,0.1449,0.1444,0.1454,33773.54
214656,2024-12-17,2034-01-02,DI1F34,2266,66395,281,806,23831842,23.406808,0.1467,0.1426,0.14512,0.1488,0.1435,0.1438,0.1431,0.14419,29783.86
214657,2024-12-17,2035-01-02,DI1F35,2514,291308,12779,35934,931749874,22.864932,0.1457,0.1402,0.14489,0.1484,0.1428,0.1431,0.1427,0.14364,26211.66
214658,2024-12-17,2036-01-02,DI1F36,2763,21985,0,0,0,22.054579,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14344,23000.21
214659,2024-12-17,2037-01-02,DI1F37,3016,4579,10,44,904728,21.203427,0.1465,0.14,0.1413,0.1465,0.144,0.142,0.1409,0.14277,20245.76
214660,2024-12-17,2038-01-04,DI1F38,3265,3522,0,0,0,20.118197,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.14277,17744.56
214661,2024-12-17,2039-01-03,DI1F39,3516,4141,0,0,0,18.968191,<NA>,<NA>,<NA>,<NA>,<NA>,0.1465,<NA>,0.14277,15535.9

In [ ]:
# df.to_parquet("../di_data.parquet", index=False, compression="gzip")

In [8]:
pd.read_parquet("../bc_secundario.parquet")

,DATA MOV,SIGLA,CODIGO,CODIGO ISIN,EMISSAO,VENCIMENTO,NUM DE OPER,QUANT NEGOCIADA,VALOR NEGOCIADO,PU MIN,PU MED,PU MAX,PU LASTRO,VALOR PAR,TAXA MIN,TAXA MED,TAXA MAX,NUM OPER COM CORRETAGEM,QUANT NEG COM CORRETAGEM
0,2003-01-02,LFT,210100,BRSTNCLF17J5,2002-08-15,2003-01-22,35,4657,7024648.13,1508.378371,1508.406336,1508.533246,1508.342193,1508.392456,-0.17,-0.02,0.02,<NA>,<NA>
1,2003-01-02,LFT,210100,BRSTNCLF1782,2002-05-16,2003-02-19,28,132379,199675891.62,1508.221527,1508.365313,1508.477934,1508.27039,1508.392456,-0.04,0.01,0.08,<NA>,<NA>
2,2003-01-02,LFT,210100,BRSTNCLF1790,2002-06-04,2003-03-19,3,1209,1823646.47,1508.392456,1508.392456,1508.392456,1508.205771,1508.392456,0.0,0.0,0.0,<NA>,<NA>
3,2003-01-02,LFT,211099,BRSTNCLF0OY7,2000-04-05,2003-04-09,10,575,901747.8,1565.866328,1568.257138,1568.43589,1568.560479,1570.226187,0.43,0.47,1.05,<NA>,<NA>
4,2003-01-02,LFT,211099,BRSTNCLF0P02,2000-04-12,2003-04-16,5,552,861814.15,1560.241691,1561.257553,1562.658741,1563.126684,1564.910568,0.51,0.82,1.05,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218858,2024-11-29,NTN-F,950199,BRSTNCNTF1P8,2016-01-15,2027-01-01,64,724609,<NA>,974.056255,981.348709,986.337225,963.936286,1000.0,<NA>,<NA>,<NA>,1,10000
218859,2024-11-29,NTN-F,950199,BRSTNCNTF1Q6,2018-01-05,2029-01-01,26,245999,<NA>,931.891017,942.491737,951.360161,911.714954,1000.0,<NA>,<NA>,<NA>,0,0
218860,2024-11-29,NTN-F,950199,BRSTNCNTF204,2020-01-10,2031-01-01,33,796203,<NA>,898.322084,918.987641,927.024511,873.015267,1000.0,<NA>,<NA>,<NA>,3,320000
218861,2024-11-29,NTN-F,950199,BRSTNCNTF212,2022-01-07,2033-01-01,11,94181,<NA>,876.127188,906.267195,907.783799,842.923447,1000.0,<NA>,<NA>,<NA>,0,0
218862,2024-11-29,NTN-F,950199,BRSTNCNTF238,2024-01-05,2035-01-01,25,1087145,<NA>,859.937135,872.604217,897.037092,820.897314,1000.0,<NA>,<NA>,<NA>,0,0