In [1]:
import polars as pl
import requests

# URL fixa para o release mais recente (Latest)
BASE_URL = "https://github.com/crdcj/pyield-data/releases/latest/download"

# Para ler o arquivo de B3 Futures
filename = "b3_futures.parquet"
response = requests.get(f"{BASE_URL}/{filename}")
df = pl.read_parquet(response.content)
df

shape: (496_367, 17)
┌────────────┬──────────┬───────────┬─────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ TradDt     ┆ TckrSymb ┆ OpnIntrst ┆ TradQty ┆ … ┆ AdjstdQt ┆ AdjstdQtTa ┆ MaxTradLmt ┆ MinTradLm │
│ ---        ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ x          ┆ ---        ┆ t         │
│ date       ┆ str      ┆ i64       ┆ i64     ┆   ┆ f64      ┆ ---        ┆ f64        ┆ ---       │
│            ┆          ┆           ┆         ┆   ┆          ┆ f64        ┆            ┆ f64       │
╞════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 2018-01-02 ┆ DAPF18   ┆ 70855     ┆ 4       ┆ … ┆ 99877.56 ┆ 3.49       ┆ 6.49       ┆ 0.49      │
│ 2018-01-02 ┆ DAPF19   ┆ 700       ┆ null    ┆ … ┆ 97172.53 ┆ 2.83       ┆ 5.81       ┆ -0.19     │
│ 2018-01-02 ┆ DAPG18   ┆ 300       ┆ null    ┆ … ┆ 99629.17 ┆ 3.17       ┆ 6.1        ┆ 0.1       │
│ 2018-01-02 ┆ DAPH18   ┆ null      ┆ null    ┆ … ┆ 99520.9  ┆ 2.45       ┆ 5.42       ┆ -0.58     │
│ 2018-01-02 ┆ DAPK19   ┆ 105039    ┆ 5       ┆ … ┆ 96586.33 ┆ 2.6        ┆ 4.67       ┆ 0.67      │
│ …          ┆ …        ┆ …         ┆ …       ┆ … ┆ …        ┆ …          ┆ …          ┆ …         │
│ 2026-07-13 ┆ WINQ26   ┆ 1097753   ┆ 4700702 ┆ … ┆ 177537.0 ┆ null       ┆ 198150.0   ┆ 162125.0  │
│ 2026-07-13 ┆ WINQ27   ┆ null      ┆ null    ┆ … ┆ 201184.0 ┆ null       ┆ 224255.0   ┆ 183485.0  │
│ 2026-07-13 ┆ WINV26   ┆ 5581      ┆ 4273    ┆ … ┆ 181306.0 ┆ null       ┆ 202350.0   ┆ 165565.0  │
│ 2026-07-13 ┆ WINV27   ┆ null      ┆ null    ┆ … ┆ 204986.0 ┆ null       ┆ 228425.0   ┆ 186900.0  │
│ 2026-07-13 ┆ WINZ26   ┆ 381       ┆ 13      ┆ … ┆ 185156.0 ┆ null       ┆ 206625.0   ┆ 169060.0  │
└────────────┴──────────┴───────────┴─────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [2]:
df.shape

(481634, 17)

In [2]:
df.filter(pl.col("TckrSymb") == "DI1F35", pl.col("TradDt") == pl.max("TradDt"))

shape: (1, 17)
┌────────────┬──────────┬───────────┬─────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ TradDt     ┆ TckrSymb ┆ OpnIntrst ┆ TradQty ┆ … ┆ AdjstdQt ┆ AdjstdQtTa ┆ MaxTradLmt ┆ MinTradLm │
│ ---        ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ x          ┆ ---        ┆ t         │
│ date       ┆ str      ┆ i64       ┆ i64     ┆   ┆ f64      ┆ ---        ┆ f64        ┆ ---       │
│            ┆          ┆           ┆         ┆   ┆          ┆ f64        ┆            ┆ f64       │
╞════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 2026-04-28 ┆ DI1F35   ┆ 726317    ┆ 11184   ┆ … ┆ 33207.01 ┆ 13.631     ┆ 14.935     ┆ 12.645    │
└────────────┴──────────┴───────────┴─────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [6]:
df["TradDt"].unique().sort()

shape: (2_066,)
Series: 'TradDt' [date]
[
	2018-01-02
	2018-01-03
	2018-01-04
	2018-01-05
	2018-01-08
	…
	2026-04-22
	2026-04-23
	2026-04-24
	2026-04-27
	2026-04-28
]

In [ ]:
# df.write_parquet(filename)