In [1]:
import pandas as pd

In [3]:
df = pd.read_parquet("../anbima_data.parquet")
df

       BondType ReferenceDate MaturityDate  IndicativeRate
0           LFT    2007-01-02   2007-01-10        -0.00015
1           LFT    2007-01-02   2007-01-17       -0.000149
2           LFT    2007-01-02   2007-02-14       -0.000154
3           LFT    2007-01-02   2007-02-21        -0.00015
4           LFT    2007-01-02   2007-03-14       -0.000148
...         ...           ...          ...             ...
219866    NTN-F    2024-11-29   2027-01-01         0.14033
219867    NTN-F    2024-11-29   2029-01-01        0.138459
219868    NTN-F    2024-11-29   2031-01-01         0.13723
219869    NTN-F    2024-11-29   2033-01-01         0.13564
219870    NTN-F    2024-11-29   2035-01-01         0.13457

[219871 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219871 entries, 0 to 219870
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   BondType        219871 non-null  string
 1   ReferenceDate   219871 non-null  datetime64[ns]
 2   MaturityDate    219871 non-null  datetime64[ns]
 3   IndicativeRate  219871 non-null  Float64
dtypes: Float64(1), datetime64[ns](2), string(1)
memory usage: 6.9 MB

In [5]:
rdate = pd.Timestamp("2024-11-14")

df.query("ReferenceDate == @rdate")

       BondType ReferenceDate MaturityDate  IndicativeRate
219401      LFT    2024-11-14   2025-03-01       -0.000124
219402      LFT    2024-11-14   2025-09-01       -0.000117
219403      LFT    2024-11-14   2026-03-01        -0.00005
219404      LFT    2024-11-14   2026-09-01             0.0
219405      LFT    2024-11-14   2027-03-01        0.000466
219406      LFT    2024-11-14   2027-09-01        0.000541
219407      LFT    2024-11-14   2028-03-01        0.000774
219408      LFT    2024-11-14   2028-09-01        0.001017
219409      LFT    2024-11-14   2029-03-01        0.001161
219410      LFT    2024-11-14   2029-09-01        0.001236
219411      LFT    2024-11-14   2030-03-01        0.001263
219412      LFT    2024-11-14   2030-06-01        0.001262
219413      LFT    2024-11-14   2030-09-01        0.001258
219414      LFT    2024-11-14   2030-12-01        0.001261
219415      LTN    2024-11-14   2025-01-01        0.113917
219416      LTN    2024-11-14   2025-04-01        0.119365
219417      LTN    2024-11-14   2025-07-01        0.124768
219418      LTN    2024-11-14   2025-10-01        0.128885
219419      LTN    2024-11-14   2026-01-01        0.131395
219420      LTN    2024-11-14   2026-04-01        0.132948
219421      LTN    2024-11-14   2026-07-01        0.133611
219422      LTN    2024-11-14   2026-10-01        0.133736
219423      LTN    2024-11-14   2027-07-01        0.133471
219424      LTN    2024-11-14   2028-01-01        0.133102
219425      LTN    2024-11-14   2028-07-01        0.133079
219426      LTN    2024-11-14   2030-01-01        0.132175
219427    NTN-B    2024-11-14   2025-05-15        0.047828
219428    NTN-B    2024-11-14   2026-08-15        0.070959
219429    NTN-B    2024-11-14   2027-05-15        0.069799
219430    NTN-B    2024-11-14   2028-08-15         0.07011
219431    NTN-B    2024-11-14   2029-05-15          0.0694
219432    NTN-B    2024-11-14   2030-08-15        0.069167
219433    NTN-B    2024-11-14   2032-08-15        0.068741
219434    NTN-B    2024-11-14   2033-05-15        0.068531
219435    NTN-B    2024-11-14   2035-05-15        0.067756
219436    NTN-B    2024-11-14   2040-08-15         0.06702
219437    NTN-B    2024-11-14   2045-05-15        0.067576
219438    NTN-B    2024-11-14   2050-08-15        0.067327
219439    NTN-B    2024-11-14   2055-05-15        0.067113
219440    NTN-B    2024-11-14   2060-08-15        0.066959
219441    NTN-C    2024-11-14   2031-01-01        0.064855
219442    NTN-F    2024-11-14   2025-01-01        0.114077
219443    NTN-F    2024-11-14   2027-01-01        0.133274
219444    NTN-F    2024-11-14   2029-01-01         0.13185
219445    NTN-F    2024-11-14   2031-01-01        0.130772
219446    NTN-F    2024-11-14   2033-01-01        0.129199
219447    NTN-F    2024-11-14   2035-01-01         0.12845

In [5]:
# df.to_parquet("../anbima_data.parquet", index=False, compression="gzip")

In [2]:
df = pd.read_parquet("../di_data.parquet")
df

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,1995-01-02,1995-02-01,DI1FEV5,22,185169,340,45045,2180001225,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,1995-01-02,1995-03-01,DI1MAR5,40,12145,21,1590,74621000,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,1995-01-02,1995-04-03,DI1ABR5,63,150,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,1995-01-03,1995-02-01,DI1FEV5,21,193594,427,81175,3932939112,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,1995-01-03,1995-03-01,DI1MAR5,39,12295,96,13425,630682950,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214391,2024-12-06,2035-01-02,DI1F35,2521,263603,8191,23454,644193100,0.1362,0.1357,0.13788,0.1396,0.1375,0.1376,0.1375,0.13859,27296.23
214392,2024-12-06,2036-01-02,DI1F36,2770,21985,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,24057.19
214393,2024-12-06,2037-01-02,DI1F37,3023,4396,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,0.1368,0.1354,0.13839,21121.78
214394,2024-12-06,2038-01-04,DI1F38,3272,3522,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,18582.73
214395,2024-12-06,2039-01-03,DI1F39,3523,4020,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,16332.09

In [3]:
df.query("TradeDate == TradeDate.max()")

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
214358,2024-12-06,2025-01-02,DI1F25,17,7611482,7613,753761,74809272281,0.1186,0.11798,0.11839,0.1186,0.11845,0.1185,0.11845,0.11851,99247.31
214359,2024-12-06,2025-02-03,DI1G25,39,519189,171,15228,1496269822,0.1198,0.1198,0.12026,0.12039,0.12035,0.12037,0.12012,0.12028,98257.59
214360,2024-12-06,2025-03-05,DI1H25,59,658865,794,27224,2649013627,0.1235,0.12333,0.1238,0.12398,0.1239,0.12393,0.1238,0.12391,97302.14
214361,2024-12-06,2025-04-01,DI1J25,78,2974087,17955,671203,64694629642,0.1261,0.1258,0.12627,0.12675,0.12645,0.1265,0.1264,0.12662,96377.05
214362,2024-12-06,2025-05-02,DI1K25,98,234394,750,57210,5456997431,0.12895,0.1288,0.12917,0.1295,0.1294,0.1294,0.12915,0.12956,95372.72
214363,2024-12-06,2025-06-02,DI1M25,119,178010,356,7519,709125125,0.1317,0.1312,0.13205,0.13245,0.1317,0.1318,0.13155,0.13217,94306.52
214364,2024-12-06,2025-07-01,DI1N25,139,2317237,33536,485864,45336408955,0.1332,0.13285,0.13373,0.1344,0.13365,0.13365,0.13355,0.13408,93295.19
214365,2024-12-06,2025-08-01,DI1Q25,162,78323,19,13371,1232278201,0.13565,0.1354,0.1354,0.1365,0.1365,0.136,0.13575,0.13645,92106.24
214366,2024-12-06,2025-09-01,DI1U25,183,128217,11,15263,1390153213,0.13765,0.1372,0.1373,0.1382,0.138,0.13855,0.13765,0.13836,91018.63
214367,2024-12-06,2025-10-01,DI1V25,205,1007173,17457,168147,15119538702,0.13865,0.1384,0.13954,0.14065,0.1396,0.13965,0.13955,0.14011,89882.32
214368,2024-12-06,2025-11-03,DI1X25,228,54075,137,9936,882280946,0.14095,0.14005,0.14034,0.14175,0.1409,0.1419,0.1409,0.14165,88704.64
214369,2024-12-06,2025-12-01,DI1Z25,247,17257,37,4134,362772870,0.1417,0.1417,0.14257,0.14325,0.14215,0.143,0.14195,0.14286,87731.92
214370,2024-12-06,2026-01-02,DI1F26,269,3370217,86690,817788,70884241594,0.14215,0.1417,0.14331,0.1449,0.1435,0.1436,0.14345,0.14404,86619.63
214371,2024-12-06,2026-04-01,DI1J26,330,655334,11525,90409,7565332959,0.144,0.14365,0.14575,0.1473,0.14555,0.14595,0.14535,0.14609,83647.25
214372,2024-12-06,2026-07-01,DI1N26,391,2168172,46483,262101,21203804955,0.1447,0.14435,0.14638,0.1485,0.14645,0.14675,0.1463,0.14719,80811.01
214373,2024-12-06,2026-10-01,DI1V26,456,374932,8663,48915,3816916129,0.145,0.1446,0.14692,0.1491,0.14695,0.1471,0.14665,0.14758,77950.93
214374,2024-12-06,2027-01-04,DI1F27,518,2457492,100653,703751,53106480426,0.1444,0.1444,0.14679,0.1493,0.1469,0.14705,0.14685,0.14759,75353.77
214375,2024-12-06,2027-04-01,DI1J27,578,135983,2245,12225,892471039,0.14455,0.1444,0.14704,0.1494,0.14695,<NA>,<NA>,0.14774,72902.07
214376,2024-12-06,2027-07-01,DI1N27,641,715235,19683,72208,5097583903,0.1443,0.1441,0.1467,0.1493,0.1467,0.1471,0.1465,0.14764,70449.07
214377,2024-12-06,2027-10-01,DI1V27,706,111980,953,6070,413611484,0.144,0.144,0.14674,0.14875,0.14635,<NA>,<NA>,0.14716,68070.38
214378,2024-12-06,2028-01-03,DI1F28,769,1079622,50619,173276,11444833769,0.14345,0.14315,0.14558,0.1482,0.14565,0.146,0.14545,0.14655,65880.53
214379,2024-12-06,2028-04-03,DI1J28,832,94891,1657,6307,402717401,0.1432,0.1431,0.14553,0.14745,0.1452,<NA>,<NA>,0.14594,63778.15
214380,2024-12-06,2028-07-03,DI1N28,893,243254,6302,31119,1926014000,0.1424,0.1424,0.14498,0.1472,0.1447,0.1452,0.1425,0.14562,61770.45
214381,2024-12-06,2028-10-02,DI1V28,957,46659,1005,5193,311099429,0.1426,0.1424,0.14444,0.14575,0.1444,<NA>,<NA>,0.14524,59749.39
214382,2024-12-06,2029-01-02,DI1F29,1017,1209754,56795,260174,15123291232,0.14155,0.14125,0.14389,0.14615,0.14375,0.14395,0.14345,0.14465,57971.39
214383,2024-12-06,2029-04-02,DI1J29,1078,47533,8,48,2721502,0.14145,0.1404,0.14184,0.1434,0.1434,<NA>,<NA>,0.14424,56192.29
214384,2024-12-06,2029-07-02,DI1N29,1141,74985,153,1039,56574167,0.1415,0.141,0.14368,0.14525,0.143,<NA>,<NA>,0.1441,54361.08
214385,2024-12-06,2029-10-01,DI1V29,1205,43153,24,358,18892359,0.1416,0.14135,0.14302,0.1438,0.1436,<NA>,<NA>,0.14362,52639.47
214386,2024-12-06,2030-01-02,DI1F30,1266,871458,18114,96955,4975423037,0.1407,0.139,0.14202,0.1446,0.142,0.1426,0.1402,0.14317,51057.83
214387,2024-12-06,2031-01-02,DI1F31,1518,756567,24572,104625,4723533284,0.1393,0.1389,0.14113,0.1432,0.1408,0.1411,0.1408,0.14192,44958.69
214388,2024-12-06,2032-01-02,DI1F32,1770,140744,986,3358,133606189,0.1384,0.1382,0.14021,0.142,0.14,<NA>,<NA>,0.14089,39621.47
214389,2024-12-06,2033-01-03,DI1F33,2022,460514,14246,50798,1787161789,0.1376,0.1371,0.13905,0.1411,0.139,0.1391,0.139,0.14002,34941.79
214390,2024-12-06,2034-01-02,DI1F34,2273,65557,156,587,18237398,0.1364,0.1364,0.13837,0.1399,0.1381,<NA>,0.1379,0.13905,30902.46
214391,2024-12-06,2035-01-02,DI1F35,2521,263603,8191,23454,644193100,0.1362,0.1357,0.13788,0.1396,0.1375,0.1376,0.1375,0.13859,27296.23
214392,2024-12-06,2036-01-02,DI1F36,2770,21985,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,24057.19
214393,2024-12-06,2037-01-02,DI1F37,3023,4396,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,0.1368,0.1354,0.13839,21121.78
214394,2024-12-06,2038-01-04,DI1F38,3272,3522,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,18582.73
214395,2024-12-06,2039-01-03,DI1F39,3523,4020,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,16332.09

In [5]:
byears = df["BDaysToExp"] / 252
dv01_price = 100_000 / ((1 + df["SettlementRate"] + 0.0001) ** byears)
df["DV01"] = (df["SettlementPrice"] - dv01_price).astype("Float64")
df

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice,DV01
0,1995-01-02,1995-02-01,DI1FEV5,22,185169,340,45045,2180001225,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31,0.56255
1,1995-01-02,1995-03-01,DI1MAR5,40,12145,21,1590,74621000,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01,1.019868
2,1995-01-02,1995-04-03,DI1ABR5,63,150,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65,1.636827
3,1995-01-03,1995-02-01,DI1FEV5,21,193594,427,81175,3932939112,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37,0.530598
4,1995-01-03,1995-03-01,DI1MAR5,39,12295,96,13425,630682950,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27,0.966267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214391,2024-12-06,2035-01-02,DI1F35,2521,263603,8191,23454,644193100,0.1362,0.1357,0.13788,0.1396,0.1375,0.1376,0.1375,0.13859,27296.23,23.971683
214392,2024-12-06,2036-01-02,DI1F36,2770,21985,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,24057.19,23.213408
214393,2024-12-06,2037-01-02,DI1F37,3023,4396,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,0.1368,0.1354,0.13839,21121.78,22.244969
214394,2024-12-06,2038-01-04,DI1F38,3272,3522,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,18582.73,21.179532
214395,2024-12-06,2039-01-03,DI1F39,3523,4020,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,16332.09,20.039441

In [7]:
cols = [
    "TradeDate",
    "ExpirationDate",
    "TickerSymbol",
    "BDaysToExp",
    "OpenContracts",
    "TradeCount",
    "TradeVolume",
    "FinancialVolume",
    "DV01",
    "OpenRate",
    "MinRate",
    "AvgRate",
    "MaxRate",
    "CloseRate",
    "CloseBidRate",
    "CloseAskRate",
    "SettlementRate",
    "SettlementPrice",
]
df = df[cols].copy()
df

,TradeDate,ExpirationDate,TickerSymbol,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,DV01,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,1995-01-02,1995-02-01,DI1FEV5,22,185169,340,45045,2180001225,0.56255,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,1995-01-02,1995-03-01,DI1MAR5,40,12145,21,1590,74621000,1.019868,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,1995-01-02,1995-04-03,DI1ABR5,63,150,0,0,0,1.636827,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,1995-01-03,1995-02-01,DI1FEV5,21,193594,427,81175,3932939112,0.530598,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,1995-01-03,1995-03-01,DI1MAR5,39,12295,96,13425,630682950,0.966267,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214391,2024-12-06,2035-01-02,DI1F35,2521,263603,8191,23454,644193100,23.971683,0.1362,0.1357,0.13788,0.1396,0.1375,0.1376,0.1375,0.13859,27296.23
214392,2024-12-06,2036-01-02,DI1F36,2770,21985,0,0,0,23.213408,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,24057.19
214393,2024-12-06,2037-01-02,DI1F37,3023,4396,0,0,0,22.244969,<NA>,<NA>,<NA>,<NA>,<NA>,0.1368,0.1354,0.13839,21121.78
214394,2024-12-06,2038-01-04,DI1F38,3272,3522,0,0,0,21.179532,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,18582.73
214395,2024-12-06,2039-01-03,DI1F39,3523,4020,0,0,0,20.039441,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.13839,16332.09

In [ ]:
# df.to_parquet("../di_data.parquet", index=False, compression="gzip")

In [8]:
pd.read_parquet("../bc_secundario.parquet")

,DATA MOV,SIGLA,CODIGO,CODIGO ISIN,EMISSAO,VENCIMENTO,NUM DE OPER,QUANT NEGOCIADA,VALOR NEGOCIADO,PU MIN,PU MED,PU MAX,PU LASTRO,VALOR PAR,TAXA MIN,TAXA MED,TAXA MAX,NUM OPER COM CORRETAGEM,QUANT NEG COM CORRETAGEM
0,2003-01-02,LFT,210100,BRSTNCLF17J5,2002-08-15,2003-01-22,35,4657,7024648.13,1508.378371,1508.406336,1508.533246,1508.342193,1508.392456,-0.17,-0.02,0.02,<NA>,<NA>
1,2003-01-02,LFT,210100,BRSTNCLF1782,2002-05-16,2003-02-19,28,132379,199675891.62,1508.221527,1508.365313,1508.477934,1508.27039,1508.392456,-0.04,0.01,0.08,<NA>,<NA>
2,2003-01-02,LFT,210100,BRSTNCLF1790,2002-06-04,2003-03-19,3,1209,1823646.47,1508.392456,1508.392456,1508.392456,1508.205771,1508.392456,0.0,0.0,0.0,<NA>,<NA>
3,2003-01-02,LFT,211099,BRSTNCLF0OY7,2000-04-05,2003-04-09,10,575,901747.8,1565.866328,1568.257138,1568.43589,1568.560479,1570.226187,0.43,0.47,1.05,<NA>,<NA>
4,2003-01-02,LFT,211099,BRSTNCLF0P02,2000-04-12,2003-04-16,5,552,861814.15,1560.241691,1561.257553,1562.658741,1563.126684,1564.910568,0.51,0.82,1.05,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218858,2024-11-29,NTN-F,950199,BRSTNCNTF1P8,2016-01-15,2027-01-01,64,724609,<NA>,974.056255,981.348709,986.337225,963.936286,1000.0,<NA>,<NA>,<NA>,1,10000
218859,2024-11-29,NTN-F,950199,BRSTNCNTF1Q6,2018-01-05,2029-01-01,26,245999,<NA>,931.891017,942.491737,951.360161,911.714954,1000.0,<NA>,<NA>,<NA>,0,0
218860,2024-11-29,NTN-F,950199,BRSTNCNTF204,2020-01-10,2031-01-01,33,796203,<NA>,898.322084,918.987641,927.024511,873.015267,1000.0,<NA>,<NA>,<NA>,3,320000
218861,2024-11-29,NTN-F,950199,BRSTNCNTF212,2022-01-07,2033-01-01,11,94181,<NA>,876.127188,906.267195,907.783799,842.923447,1000.0,<NA>,<NA>,<NA>,0,0
218862,2024-11-29,NTN-F,950199,BRSTNCNTF238,2024-01-05,2035-01-01,25,1087145,<NA>,859.937135,872.604217,897.037092,820.897314,1000.0,<NA>,<NA>,<NA>,0,0