In [2]:
import polars as pl
import requests

# URL fixa para o release mais recente (Latest)
BASE_URL = "https://github.com/crdcj/pyield-data/releases/latest/download"

# Para ler o arquivo de ANBIMA TPF
response = requests.get(f"{BASE_URL}/anbima_tpf.parquet")
df = pl.read_parquet(response.content)

df

shape: (76_579, 9)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ data_refer ┆ titulo ┆ codigo_sel ┆ data_base ┆ … ┆ pu        ┆ taxa_comp ┆ taxa_vend ┆ taxa_indi │
│ encia      ┆ ---    ┆ ic         ┆ ---       ┆   ┆ ---       ┆ ra        ┆ a         ┆ cativa    │
│ ---        ┆ str    ┆ ---        ┆ date      ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│ date       ┆        ┆ i64        ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2020-01-02 ┆ LFT    ┆ 210100     ┆ 2000-07-0 ┆ … ┆ 10471.849 ┆ null      ┆ null      ┆ 0.000023  │
│            ┆        ┆            ┆ 1         ┆   ┆ 015       ┆           ┆           ┆           │
│ 2020-01-02 ┆ LFT    ┆ 210100     ┆ 2000-07-0 ┆ … ┆ 10471.723 ┆ null      ┆ null      ┆ 0.000023  │
│            ┆        ┆            ┆ 1         ┆   ┆ 352       ┆           ┆           ┆           │
│ 2020-01-02 ┆ LFT    ┆ 210100     ┆ 2000-07-0 ┆ … ┆ 10471.356 ┆ null      ┆ null      ┆ 0.000044  │
│            ┆        ┆            ┆ 1         ┆   ┆ 836       ┆           ┆           ┆           │
│ 2020-01-02 ┆ LFT    ┆ 210100     ┆ 2000-07-0 ┆ … ┆ 10470.917 ┆ null      ┆ null      ┆ 0.000056  │
│            ┆        ┆            ┆ 1         ┆   ┆ 017       ┆           ┆           ┆           │
│ 2020-01-02 ┆ LFT    ┆ 210100     ┆ 2000-07-0 ┆ … ┆ 10470.016 ┆ null      ┆ null      ┆ 0.000083  │
│            ┆        ┆            ┆ 1         ┆   ┆ 434       ┆           ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-09-01 ┆ NTN-F  ┆ 950199     ┆ 2018-01-0 ┆ … ┆ 945.15847 ┆ 0.140123  ┆ 0.139717  ┆ 0.139932  │
│            ┆        ┆            ┆ 5         ┆   ┆ 9         ┆           ┆           ┆           │
│ 2026-09-01 ┆ NTN-F  ┆ 950199     ┆ 2020-01-1 ┆ … ┆ 885.06312 ┆ 0.14503   ┆ 0.144912  ┆ 0.144974  │
│            ┆        ┆            ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│ 2026-09-01 ┆ NTN-F  ┆ 950199     ┆ 2022-01-0 ┆ … ┆ 841.28331 ┆ 0.146117  ┆ 0.146002  ┆ 0.146065  │
│            ┆        ┆            ┆ 7         ┆   ┆ 1         ┆           ┆           ┆           │
│ 2026-09-01 ┆ NTN-F  ┆ 950199     ┆ 2024-01-0 ┆ … ┆ 810.54286 ┆ 0.146323  ┆ 0.14611   ┆ 0.14621   │
│            ┆        ┆            ┆ 5         ┆   ┆ 1         ┆           ┆           ┆           │
│ 2026-09-01 ┆ NTN-F  ┆ 950199     ┆ 2026-01-0 ┆ … ┆ 788.40800 ┆ 0.145966  ┆ 0.145793  ┆ 0.145887  │
│            ┆        ┆            ┆ 9         ┆   ┆ 4         ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
df["data_referencia"].unique().sort()

shape: (1_574,)
Series: 'data_referencia' [date]
[
	2020-01-02
	2020-01-03
	2020-01-06
	2020-01-07
	2020-01-08
	…
	2026-04-22
	2026-04-23
	2026-04-24
	2026-04-27
	2026-04-28
]

In [ ]:
# df.write_parquet("anbima_tpf.parquet")