In [9]:
import pandas as pd

df = pd.read_parquet("../data/anbima_tpf.parquet")
df

,BondType,ReferenceDate,SelicCode,IssueBaseDate,MaturityDate,BDToMat,Duration,DV01,DV01USD,Price,BidRate,AskRate,IndicativeRate,DIRate
0,LFT,2020-01-02,210100,2000-07-01,2020-03-01,40,0.0,0.0,0.0,10471.849015,<NA>,<NA>,0.000023,0.04375
1,LFT,2020-01-02,210100,2000-07-01,2020-09-01,167,0.0,0.0,0.0,10471.723352,<NA>,<NA>,0.000023,0.04344
2,LFT,2020-01-02,210100,2000-07-01,2021-03-01,289,0.0,0.0,0.0,10471.356836,<NA>,<NA>,0.000044,0.046359
3,LFT,2020-01-02,210100,2000-07-01,2021-09-01,418,0.0,0.0,0.0,10470.917017,<NA>,<NA>,0.000056,0.050221
4,LFT,2020-01-02,210100,2000-07-01,2022-03-01,542,0.0,0.0,0.0,10470.016434,<NA>,<NA>,0.000083,0.053607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63857,NTN-F,2025-08-26,950199,2016-01-15,2027-01-01,339,1.275077,0.108567,0.020025,970.195537,0.139582,0.139328,0.13946,0.1398
63858,NTN-F,2025-08-26,950199,2018-01-05,2029-01-01,838,2.853494,0.234469,0.043248,931.709383,0.133983,0.133781,0.133895,0.13246
63859,NTN-F,2025-08-26,950199,2020-01-10,2031-01-01,1339,4.108755,0.318707,0.058786,882.82519,0.138196,0.138064,0.138133,0.13587
63860,NTN-F,2025-08-26,950199,2022-01-07,2033-01-01,1843,5.089522,0.379147,0.069934,848.53246,0.139154,0.13895,0.139038,0.13768
63861,NTN-F,2025-08-26,950199,2024-01-05,2035-01-01,2342,5.823301,0.418689,0.077228,819.856662,0.140404,0.140214,0.14029,0.13804

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63862 entries, 0 to 63861
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BondType        63862 non-null  object
 1   ReferenceDate   63862 non-null  date32[day][pyarrow]
 2   SelicCode       63862 non-null  int64[pyarrow]
 3   IssueBaseDate   63862 non-null  date32[day][pyarrow]
 4   MaturityDate    63862 non-null  date32[day][pyarrow]
 5   BDToMat         63862 non-null  int64[pyarrow]
 6   Duration        63862 non-null  double[pyarrow]
 7   DV01            63862 non-null  double[pyarrow]
 8   DV01USD         63862 non-null  double[pyarrow]
 9   Price           63862 non-null  double[pyarrow]
 10  BidRate         61041 non-null  double[pyarrow]
 11  AskRate         61038 non-null  double[pyarrow]
 12  IndicativeRate  63862 non-null  double[pyarrow]
 13  DIRate          63862 non-null  double[pyarrow]
dtypes: date32[day][pyarrow](3), double[pyarrow](8), int64[pyarrow](2), object(1)
memory usage: 6.2+ MB

In [11]:
df["BondType"] = df["BondType"].astype("string")

In [12]:
select_cols = [
    "ReferenceDate",
    "BondType",
    "SelicCode",
    "IssueBaseDate",
    "MaturityDate",
    "BDToMat",
    "Duration",
    "DV01",
    "DV01USD",
    "Price",
    "BidRate",
    "AskRate",
    "IndicativeRate",
    "DIRate",
]
df = df[select_cols].copy()
df

,ReferenceDate,BondType,SelicCode,IssueBaseDate,MaturityDate,BDToMat,Duration,DV01,DV01USD,Price,BidRate,AskRate,IndicativeRate,DIRate
0,2020-01-02,LFT,210100,2000-07-01,2020-03-01,40,0.0,0.0,0.0,10471.849015,<NA>,<NA>,0.000023,0.04375
1,2020-01-02,LFT,210100,2000-07-01,2020-09-01,167,0.0,0.0,0.0,10471.723352,<NA>,<NA>,0.000023,0.04344
2,2020-01-02,LFT,210100,2000-07-01,2021-03-01,289,0.0,0.0,0.0,10471.356836,<NA>,<NA>,0.000044,0.046359
3,2020-01-02,LFT,210100,2000-07-01,2021-09-01,418,0.0,0.0,0.0,10470.917017,<NA>,<NA>,0.000056,0.050221
4,2020-01-02,LFT,210100,2000-07-01,2022-03-01,542,0.0,0.0,0.0,10470.016434,<NA>,<NA>,0.000083,0.053607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63857,2025-08-26,NTN-F,950199,2016-01-15,2027-01-01,339,1.275077,0.108567,0.020025,970.195537,0.139582,0.139328,0.13946,0.1398
63858,2025-08-26,NTN-F,950199,2018-01-05,2029-01-01,838,2.853494,0.234469,0.043248,931.709383,0.133983,0.133781,0.133895,0.13246
63859,2025-08-26,NTN-F,950199,2020-01-10,2031-01-01,1339,4.108755,0.318707,0.058786,882.82519,0.138196,0.138064,0.138133,0.13587
63860,2025-08-26,NTN-F,950199,2022-01-07,2033-01-01,1843,5.089522,0.379147,0.069934,848.53246,0.139154,0.13895,0.139038,0.13768
63861,2025-08-26,NTN-F,950199,2024-01-05,2035-01-01,2342,5.823301,0.418689,0.077228,819.856662,0.140404,0.140214,0.14029,0.13804

In [13]:
df.to_parquet("../data/anbima_tpf.parquet", index=False, compression="gzip")