In [1]:
import polars as pl
import requests

# URL fixa para o release mais recente (Latest)
BASE_URL = "https://github.com/crdcj/pyield-data/releases/latest/download"

# Para ler o arquivo de B3 Futures
filename = "b3_futures.parquet"
response = requests.get(f"{BASE_URL}/{filename}")
df = pl.read_parquet(response.content)
df

shape: (477_360, 17)
┌────────────┬──────────┬───────────┬─────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ TradDt     ┆ TckrSymb ┆ OpnIntrst ┆ TradQty ┆ … ┆ AdjstdQt ┆ AdjstdQtTa ┆ MaxTradLmt ┆ MinTradLm │
│ ---        ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ x          ┆ ---        ┆ t         │
│ date       ┆ str      ┆ i64       ┆ i64     ┆   ┆ f64      ┆ ---        ┆ f64        ┆ ---       │
│            ┆          ┆           ┆         ┆   ┆          ┆ f64        ┆            ┆ f64       │
╞════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 2018-01-02 ┆ DAPF18   ┆ 70855     ┆ 4       ┆ … ┆ 99877.56 ┆ 3.49       ┆ 6.49       ┆ 0.49      │
│ 2018-01-02 ┆ DAPF19   ┆ 700       ┆ null    ┆ … ┆ 97172.53 ┆ 2.83       ┆ 5.81       ┆ -0.19     │
│ 2018-01-02 ┆ DAPG18   ┆ 300       ┆ null    ┆ … ┆ 99629.17 ┆ 3.17       ┆ 6.1        ┆ 0.1       │
│ 2018-01-02 ┆ DAPH18   ┆ null      ┆ null    ┆ … ┆ 99520.9  ┆ 2.45       ┆ 5.42       ┆ -0.58     │
│ 2018-01-02 ┆ DAPK19   ┆ 105039    ┆ 5       ┆ … ┆ 96586.33 ┆ 2.6        ┆ 4.67       ┆ 0.67      │
│ …          ┆ …        ┆ …         ┆ …       ┆ … ┆ …        ┆ …          ┆ …          ┆ …         │
│ 2026-04-06 ┆ WINQ26   ┆ 34817     ┆ 15      ┆ … ┆ 196639.0 ┆ null       ┆ 216195.0   ┆ 176890.0  │
│ 2026-04-06 ┆ WINQ27   ┆ null      ┆ null    ┆ … ┆ 221512.0 ┆ null       ┆ 244275.0   ┆ 199865.0  │
│ 2026-04-06 ┆ WINV26   ┆ null      ┆ null    ┆ … ┆ 200727.0 ┆ null       ┆ 220780.0   ┆ 180640.0  │
│ 2026-04-06 ┆ WINV27   ┆ null      ┆ null    ┆ … ┆ 225413.0 ┆ null       ┆ 248720.0   ┆ 203505.0  │
│ 2026-04-06 ┆ WINZ26   ┆ null      ┆ null    ┆ … ┆ 204863.0 ┆ null       ┆ 225430.0   ┆ 184450.0  │
└────────────┴──────────┴───────────┴─────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [5]:
df.filter(pl.col("TckrSymb") == "DI1F35", pl.col("TradDt") == pl.max("TradDt"))

shape: (1, 17)
┌────────────┬──────────┬───────────┬─────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ TradDt     ┆ TckrSymb ┆ OpnIntrst ┆ TradQty ┆ … ┆ AdjstdQt ┆ AdjstdQtTa ┆ MaxTradLmt ┆ MinTradLm │
│ ---        ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ x          ┆ ---        ┆ t         │
│ date       ┆ str      ┆ i64       ┆ i64     ┆   ┆ f64      ┆ ---        ┆ f64        ┆ ---       │
│            ┆          ┆           ┆         ┆   ┆          ┆ f64        ┆            ┆ f64       │
╞════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 2026-04-06 ┆ DI1F35   ┆ 719767    ┆ 8020    ┆ … ┆ 32403.83 ┆ null       ┆ 15.185     ┆ 12.9      │
└────────────┴──────────┴───────────┴─────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [2]:
df.columns

['TradDt',
 'TckrSymb',
 'OpnIntrst',
 'TradQty',
 'FinInstrmQty',
 'NtlFinVol',
 'BestBidPric',
 'BestAskPric',
 'FrstPric',
 'MinPric',
 'MaxPric',
 'TradAvrgPric',
 'LastPric',
 'AdjstdQt',
 'AdjstdQtTax',
 'MaxTradLmt',
 'MinTradLmt']

In [8]:
df.write_parquet(filename)