In [6]:
import pandas as pd

In [7]:
df = pd.read_parquet("../anbima_data.parquet")
df

       BondType ReferenceDate MaturityDate  IndicativeRate
0           LFT    2007-01-02   2007-01-10        -0.00015
1           LFT    2007-01-02   2007-01-17       -0.000149
2           LFT    2007-01-02   2007-02-14       -0.000154
3           LFT    2007-01-02   2007-02-21        -0.00015
4           LFT    2007-01-02   2007-03-14       -0.000148
...         ...           ...          ...             ...
219819    NTN-F    2024-11-28   2027-01-01        0.139235
219820    NTN-F    2024-11-28   2029-01-01        0.138025
219821    NTN-F    2024-11-28   2031-01-01        0.137122
219822    NTN-F    2024-11-28   2033-01-01        0.135701
219823    NTN-F    2024-11-28   2035-01-01        0.134856

[219824 rows x 4 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219824 entries, 0 to 219823
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   BondType        219824 non-null  string
 1   ReferenceDate   219824 non-null  datetime64[ns]
 2   MaturityDate    219824 non-null  datetime64[ns]
 3   IndicativeRate  219824 non-null  Float64
dtypes: Float64(1), datetime64[ns](2), string(1)
memory usage: 6.9 MB

In [9]:
rdate = pd.Timestamp("2024-11-14")

df.query("ReferenceDate == @rdate")

       BondType ReferenceDate MaturityDate  IndicativeRate
219401      LFT    2024-11-14   2025-03-01       -0.000124
219402      LFT    2024-11-14   2025-09-01       -0.000117
219403      LFT    2024-11-14   2026-03-01        -0.00005
219404      LFT    2024-11-14   2026-09-01             0.0
219405      LFT    2024-11-14   2027-03-01        0.000466
219406      LFT    2024-11-14   2027-09-01        0.000541
219407      LFT    2024-11-14   2028-03-01        0.000774
219408      LFT    2024-11-14   2028-09-01        0.001017
219409      LFT    2024-11-14   2029-03-01        0.001161
219410      LFT    2024-11-14   2029-09-01        0.001236
219411      LFT    2024-11-14   2030-03-01        0.001263
219412      LFT    2024-11-14   2030-06-01        0.001262
219413      LFT    2024-11-14   2030-09-01        0.001258
219414      LFT    2024-11-14   2030-12-01        0.001261
219415      LTN    2024-11-14   2025-01-01        0.113917
219416      LTN    2024-11-14   2025-04-01        0.119365
219417      LTN    2024-11-14   2025-07-01        0.124768
219418      LTN    2024-11-14   2025-10-01        0.128885
219419      LTN    2024-11-14   2026-01-01        0.131395
219420      LTN    2024-11-14   2026-04-01        0.132948
219421      LTN    2024-11-14   2026-07-01        0.133611
219422      LTN    2024-11-14   2026-10-01        0.133736
219423      LTN    2024-11-14   2027-07-01        0.133471
219424      LTN    2024-11-14   2028-01-01        0.133102
219425      LTN    2024-11-14   2028-07-01        0.133079
219426      LTN    2024-11-14   2030-01-01        0.132175
219427    NTN-B    2024-11-14   2025-05-15        0.047828
219428    NTN-B    2024-11-14   2026-08-15        0.070959
219429    NTN-B    2024-11-14   2027-05-15        0.069799
219430    NTN-B    2024-11-14   2028-08-15         0.07011
219431    NTN-B    2024-11-14   2029-05-15          0.0694
219432    NTN-B    2024-11-14   2030-08-15        0.069167
219433    NTN-B    2024-11-14   2032-08-15        0.068741
219434    NTN-B    2024-11-14   2033-05-15        0.068531
219435    NTN-B    2024-11-14   2035-05-15        0.067756
219436    NTN-B    2024-11-14   2040-08-15         0.06702
219437    NTN-B    2024-11-14   2045-05-15        0.067576
219438    NTN-B    2024-11-14   2050-08-15        0.067327
219439    NTN-B    2024-11-14   2055-05-15        0.067113
219440    NTN-B    2024-11-14   2060-08-15        0.066959
219441    NTN-C    2024-11-14   2031-01-01        0.064855
219442    NTN-F    2024-11-14   2025-01-01        0.114077
219443    NTN-F    2024-11-14   2027-01-01        0.133274
219444    NTN-F    2024-11-14   2029-01-01         0.13185
219445    NTN-F    2024-11-14   2031-01-01        0.130772
219446    NTN-F    2024-11-14   2033-01-01        0.129199
219447    NTN-F    2024-11-14   2035-01-01         0.12845

In [10]:
# df.to_parquet("../anbima_data.parquet", index=False, compression="gzip")

In [11]:
df = pd.read_parquet("../di_data.parquet")
df

,TickerSymbol,TradeDate,ExpirationDate,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,DI1FEV5,1995-01-02,1995-02-01,22,185169,340,45045,2180001225,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,DI1MAR5,1995-01-02,1995-03-01,40,12145,21,1590,74621000,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,DI1ABR5,1995-01-02,1995-04-03,63,150,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,DI1FEV5,1995-01-03,1995-02-01,21,193594,427,81175,3932939112,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,DI1MAR5,1995-01-03,1995-03-01,39,12295,96,13425,630682950,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214163,DI1F35,2024-11-28,2035-01-02,2527,241539,4495,22430,638044329,0.132,0.1316,0.13357,0.1353,0.1352,0.1354,0.135,0.134,28336.91
214164,DI1F36,2024-11-28,2036-01-02,2776,21985,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.1338,25074.56
214165,DI1F37,2024-11-28,2037-01-02,3029,4396,1,10,225306,0.132,0.132,0.132,0.132,0.132,0.1345,<NA>,0.1338,22104.49
214166,DI1F38,2024-11-28,2038-01-04,3278,3522,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.1338,19525.1
214167,DI1F39,2024-11-28,2039-01-03,3529,4020,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.1338,17229.52

In [12]:
df.query("TradeDate == @rdate")

,TickerSymbol,TradeDate,ExpirationDate,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
213826,DI1Z24,2024-11-14,2024-12-02,10,2197681,94,23589,2349021190,0.11156,0.11154,0.11155,0.11156,0.11156,0.11156,0.11154,0.11154,99581.25
213827,DI1F25,2024-11-14,2025-01-02,31,5480816,2860,203150,20046563573,0.11416,0.11412,0.11419,0.11436,0.1142,0.1142,0.11418,0.1142,98678.56
213828,DI1G25,2024-11-14,2025-02-03,53,398719,278,17853,1744545322,0.11598,0.11596,0.11605,0.11614,0.11608,0.11612,0.11604,0.11603,97717.63
213829,DI1H25,2024-11-14,2025-03-05,73,453546,287,19823,1919042068,0.1186,0.11835,0.11846,0.11865,0.1185,0.1187,0.1184,0.11843,96809.7
213830,DI1J25,2024-11-14,2025-04-01,92,2221008,8503,243379,23349000233,0.12035,0.1202,0.12032,0.12065,0.1205,0.12055,0.1205,0.12031,95937.33
213831,DI1K25,2024-11-14,2025-05-02,112,195492,52,16799,1595861232,0.1225,0.12225,0.1224,0.1226,0.1226,0.1228,0.1225,0.12242,94996.74
213832,DI1M25,2024-11-14,2025-06-02,133,146717,8,542,50945893,0.1246,0.12395,0.12447,0.1246,0.1243,0.12455,0.1243,0.12416,94010.0
213833,DI1N25,2024-11-14,2025-07-01,153,2221391,16357,345206,32124727411,0.12585,0.12545,0.12577,0.12645,0.1261,0.12625,0.1261,0.12576,93060.43
213834,DI1Q25,2024-11-14,2025-08-01,176,61521,10,651,59876120,0.1272,0.127,0.12723,0.1274,0.1274,0.1281,0.1275,0.12727,91973.56
213835,DI1U25,2024-11-14,2025-09-01,197,111266,6,419,38127853,0.1285,0.1281,0.12826,0.1285,0.12845,0.1294,0.12865,0.12838,90989.91
213836,DI1V25,2024-11-14,2025-10-01,219,957401,7225,113442,10203712554,0.1298,0.12925,0.12966,0.1304,0.13005,0.13015,0.12995,0.12952,89956.52
213837,DI1X25,2024-11-14,2025-11-03,242,41464,13,200,17779065,0.1307,0.1303,0.1304,0.1307,0.13065,0.1315,0.1307,0.13036,88898.62
213838,DI1F26,2024-11-14,2026-01-02,283,3388267,45702,596193,51872208895,0.1318,0.13135,0.13195,0.1327,0.13235,0.1325,0.13235,0.13174,87024.52
213839,DI1J26,2024-11-14,2026-04-01,344,620266,2823,34818,2935516587,0.1331,0.1326,0.13317,0.13395,0.1337,0.1339,0.13365,0.13302,84325.98
213840,DI1N26,2024-11-14,2026-07-01,405,2141742,16729,99167,8106221971,0.1334,0.13305,0.13363,0.13455,0.13445,0.1345,0.13435,0.1336,81747.65
213841,DI1V26,2024-11-14,2026-10-01,470,348944,3651,34575,2736174920,0.13365,0.13305,0.13366,0.1346,0.13455,0.13465,0.1344,0.13371,79131.52
213842,DI1F27,2024-11-14,2027-01-04,532,2466172,38418,370813,28457634578,0.1335,0.13275,0.13358,0.13445,0.1344,0.1344,0.1343,0.13355,76748.46
213843,DI1J27,2024-11-14,2027-04-01,592,128923,408,3968,295698793,0.13355,0.13285,0.13336,0.1342,0.1342,0.1345,<NA>,0.13337,74519.45
213844,DI1N27,2024-11-14,2027-07-01,655,615488,6893,34431,2487219416,0.1333,0.13255,0.13328,0.13425,0.1342,0.1343,0.13415,0.13338,72221.54
213845,DI1V27,2024-11-14,2027-10-01,720,97856,58,7228,505793924,0.1335,0.13255,0.13309,0.1338,0.1338,<NA>,0.1326,0.13315,69966.98
213846,DI1F28,2024-11-14,2028-01-03,783,1065200,15647,82573,5607490729,0.13265,0.13195,0.13263,0.13355,0.13355,0.1337,0.1333,0.13274,67890.6
213847,DI1J28,2024-11-14,2028-04-03,846,76970,63,905,59624195,0.1328,0.1318,0.13235,0.1331,0.1331,<NA>,<NA>,0.13255,65844.82
213848,DI1N28,2024-11-14,2028-07-03,907,224271,1713,24594,1572212300,0.1323,0.13165,0.13237,0.13315,0.13315,0.13325,0.133,0.13245,63910.81
213849,DI1V28,2024-11-14,2028-10-02,971,43380,213,1538,95390976,0.1323,0.13145,0.13197,0.13285,0.13285,<NA>,<NA>,0.13223,61969.84
213850,DI1F29,2024-11-14,2029-01-02,1031,1225751,29032,187981,11328489676,0.13135,0.13105,0.13177,0.13255,0.1325,0.1325,0.1324,0.13185,60246.97
213851,DI1J29,2024-11-14,2029-04-02,1092,47043,4,87,5095282,0.1312,0.1312,0.1314,0.13165,0.13165,<NA>,<NA>,0.13159,58525.78
213852,DI1N29,2024-11-14,2029-07-02,1155,71972,7,46,2610321,0.13135,0.13135,0.13158,0.13185,0.1317,<NA>,<NA>,0.13141,56786.04
213853,DI1V29,2024-11-14,2029-10-01,1219,25204,29,303,16704389,0.13145,0.1307,0.13099,0.1317,0.1317,<NA>,<NA>,0.13119,55084.87
213854,DI1F30,2024-11-14,2030-01-02,1280,834220,4991,46946,2512493257,0.1308,0.1304,0.13096,0.1319,0.1318,0.1319,0.1316,0.13115,53475.07
213855,DI1F31,2024-11-14,2031-01-02,1532,752020,12386,78791,3745081068,0.1296,0.1294,0.13014,0.131,0.1309,0.1309,0.1308,0.13028,47496.61
213856,DI1F32,2024-11-14,2032-01-02,1784,133656,70,308,13004362,0.1291,0.1288,0.12952,0.1302,0.1301,<NA>,<NA>,0.1295,42227.86
213857,DI1F33,2024-11-14,2033-01-03,2036,464296,4401,15956,599676291,0.1285,0.1282,0.12876,0.1297,0.1296,0.1297,0.1295,0.12901,37517.62
213858,DI1F34,2024-11-14,2034-01-02,2287,57749,47,568,19005388,0.1281,0.1273,0.12821,0.1288,0.1287,0.129,0.1285,0.12817,33471.89
213859,DI1F35,2024-11-14,2035-01-02,2535,231958,1286,13049,390095351,0.1272,0.1271,0.12753,0.1286,0.1284,0.1285,0.1284,0.1279,29797.7
213860,DI1F36,2024-11-14,2036-01-02,2784,21985,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.1277,26508.5
213861,DI1F37,2024-11-14,2037-01-02,3037,4146,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,0.1283,0.1274,0.1277,23495.49
213862,DI1F38,2024-11-14,2038-01-04,3286,3754,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.1277,20864.71
213863,DI1F39,2024-11-14,2039-01-03,3537,2310,1,200,3743886,0.1268,0.1268,0.1268,0.1268,0.1268,<NA>,<NA>,0.1277,18510.83

In [3]:
pd.read_parquet("../bc_secundario.parquet")

,DATA MOV,SIGLA,CODIGO,CODIGO ISIN,EMISSAO,VENCIMENTO,NUM DE OPER,QUANT NEGOCIADA,VALOR NEGOCIADO,PU MIN,PU MED,PU MAX,PU LASTRO,VALOR PAR,TAXA MIN,TAXA MED,TAXA MAX,NUM OPER COM CORRETAGEM,QUANT NEG COM CORRETAGEM
0,2003-01-02,LFT,210100,BRSTNCLF17J5,2002-08-15,2003-01-22,35,4657,7024648.13,1508.378371,1508.406336,1508.533246,1508.342193,1508.392456,-0.17,-0.02,0.02,<NA>,<NA>
1,2003-01-02,LFT,210100,BRSTNCLF1782,2002-05-16,2003-02-19,28,132379,199675891.62,1508.221527,1508.365313,1508.477934,1508.27039,1508.392456,-0.04,0.01,0.08,<NA>,<NA>
2,2003-01-02,LFT,210100,BRSTNCLF1790,2002-06-04,2003-03-19,3,1209,1823646.47,1508.392456,1508.392456,1508.392456,1508.205771,1508.392456,0.0,0.0,0.0,<NA>,<NA>
3,2003-01-02,LFT,211099,BRSTNCLF0OY7,2000-04-05,2003-04-09,10,575,901747.8,1565.866328,1568.257138,1568.43589,1568.560479,1570.226187,0.43,0.47,1.05,<NA>,<NA>
4,2003-01-02,LFT,211099,BRSTNCLF0P02,2000-04-12,2003-04-16,5,552,861814.15,1560.241691,1561.257553,1562.658741,1563.126684,1564.910568,0.51,0.82,1.05,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216190,2024-09-06,NTN-F,950199,BRSTNCNTF1P8,2016-01-15,2027-01-01,11,74589,<NA>,981.590929,984.163864,986.696412,975.111307,1000.0,<NA>,<NA>,<NA>,0,0
216191,2024-09-06,NTN-F,950199,BRSTNCNTF1Q6,2018-01-05,2029-01-01,17,69957,<NA>,952.927941,956.996934,961.176823,942.357342,1000.0,<NA>,<NA>,<NA>,0,0
216192,2024-09-06,NTN-F,950199,BRSTNCNTF204,2020-01-10,2031-01-01,38,1760798,<NA>,930.348258,937.40593,940.320868,916.20393,1000.0,<NA>,<NA>,<NA>,4,200000
216193,2024-09-06,NTN-F,950199,BRSTNCNTF212,2022-01-07,2033-01-01,20,309758,<NA>,916.517448,922.466269,930.200213,895.480003,1000.0,<NA>,<NA>,<NA>,0,0
216194,2024-09-06,NTN-F,950199,BRSTNCNTF238,2024-01-05,2035-01-01,26,523535,<NA>,903.712064,912.357687,916.194949,879.206445,1000.0,<NA>,<NA>,<NA>,3,150000