In [2]:
import pandas as pd

In [4]:
pd.read_parquet("../anbima_data.parquet")

,BondType,ReferenceDate,MaturityDate,IndicativeRate,DIRate,DISpread,DINetSpread,Premium,SpotRate,BEI
0,LFT,2007-01-02,2007-01-10,-0.00015,0.1309,<NA>,<NA>,0.998789,<NA>,<NA>
1,LFT,2007-01-02,2007-01-17,-0.000149,0.1309,<NA>,<NA>,0.998797,<NA>,<NA>
2,LFT,2007-01-02,2007-02-14,-0.000154,0.130061,<NA>,<NA>,0.998757,<NA>,<NA>
3,LFT,2007-01-02,2007-02-21,-0.00015,0.12988,<NA>,<NA>,0.998789,<NA>,<NA>
4,LFT,2007-01-02,2007-03-14,-0.000148,0.128875,<NA>,<NA>,0.998805,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...
217141,NTN-F,2024-09-06,2027-01-01,0.117211,0.11692,2.91,3.49,1.002823,<NA>,<NA>
217142,NTN-F,2024-09-06,2029-01-01,0.118457,0.11788,5.77,7.25,1.005822,<NA>,<NA>
217143,NTN-F,2024-09-06,2031-01-01,0.118958,0.11782,11.38,12.24,1.009828,<NA>,<NA>
217144,NTN-F,2024-09-06,2033-01-01,0.118107,0.11749,6.17,5.94,1.004783,<NA>,<NA>
217145,NTN-F,2024-09-06,2035-01-01,0.118336,0.1172,11.36,10.18,1.00821,<NA>,<NA>

In [3]:
pd.read_parquet("../di_data.parquet")

,TickerSymbol,TradeDate,ExpirationDate,BDaysToExp,OpenContracts,TradeCount,TradeVolume,FinancialVolume,OpenRate,MinRate,AvgRate,MaxRate,CloseRate,CloseBidRate,CloseAskRate,SettlementRate,SettlementPrice
0,DI1FEV5,1995-01-02,1995-02-01,22,185169,340,45045,2180001225,0.44285,0.44285,0.45276,0.46003,0.45485,<NA>,<NA>,0.45721,96766.31
1,DI1MAR5,1995-01-02,1995-03-01,40,12145,21,1590,74621000,0.49064,0.48964,0.49035,0.49264,0.49014,<NA>,<NA>,0.48974,93869.01
2,DI1ABR5,1995-01-02,1995-04-03,63,150,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.45662,91025.65
3,DI1FEV5,1995-01-03,1995-02-01,21,193594,427,81175,3932939112,0.4592,0.45559,0.45915,0.46463,0.45739,<NA>,<NA>,0.45949,96898.37
4,DI1MAR5,1995-01-03,1995-03-01,39,12295,96,13425,630682950,0.49154,0.48643,0.49601,0.50184,0.49565,<NA>,<NA>,0.49665,93950.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211996,DI1F35,2024-09-06,2035-01-02,2584,215354,2295,27440,879636840,0.117,0.1163,0.11733,0.1178,0.1173,0.1175,0.1173,0.1172,32097.19
211997,DI1F36,2024-09-06,2036-01-02,2833,21980,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,0.1182,0.1166,0.117,28825.92
211998,DI1F37,2024-09-06,2037-01-02,3086,3646,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.117,25795.22
211999,DI1F38,2024-09-06,2038-01-04,3335,2200,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.117,23123.75
212000,DI1F39,2024-09-06,2039-01-03,3586,0,0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.117,20710.74

In [3]:
pd.read_parquet("../bc_secundario.parquet")

,DATA MOV,SIGLA,CODIGO,CODIGO ISIN,EMISSAO,VENCIMENTO,NUM DE OPER,QUANT NEGOCIADA,VALOR NEGOCIADO,PU MIN,PU MED,PU MAX,PU LASTRO,VALOR PAR,TAXA MIN,TAXA MED,TAXA MAX,NUM OPER COM CORRETAGEM,QUANT NEG COM CORRETAGEM
0,2003-01-02,LFT,210100,BRSTNCLF17J5,2002-08-15,2003-01-22,35,4657,7024648.13,1508.378371,1508.406336,1508.533246,1508.342193,1508.392456,-0.17,-0.02,0.02,<NA>,<NA>
1,2003-01-02,LFT,210100,BRSTNCLF1782,2002-05-16,2003-02-19,28,132379,199675891.62,1508.221527,1508.365313,1508.477934,1508.27039,1508.392456,-0.04,0.01,0.08,<NA>,<NA>
2,2003-01-02,LFT,210100,BRSTNCLF1790,2002-06-04,2003-03-19,3,1209,1823646.47,1508.392456,1508.392456,1508.392456,1508.205771,1508.392456,0.0,0.0,0.0,<NA>,<NA>
3,2003-01-02,LFT,211099,BRSTNCLF0OY7,2000-04-05,2003-04-09,10,575,901747.8,1565.866328,1568.257138,1568.43589,1568.560479,1570.226187,0.43,0.47,1.05,<NA>,<NA>
4,2003-01-02,LFT,211099,BRSTNCLF0P02,2000-04-12,2003-04-16,5,552,861814.15,1560.241691,1561.257553,1562.658741,1563.126684,1564.910568,0.51,0.82,1.05,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216190,2024-09-06,NTN-F,950199,BRSTNCNTF1P8,2016-01-15,2027-01-01,11,74589,<NA>,981.590929,984.163864,986.696412,975.111307,1000.0,<NA>,<NA>,<NA>,0,0
216191,2024-09-06,NTN-F,950199,BRSTNCNTF1Q6,2018-01-05,2029-01-01,17,69957,<NA>,952.927941,956.996934,961.176823,942.357342,1000.0,<NA>,<NA>,<NA>,0,0
216192,2024-09-06,NTN-F,950199,BRSTNCNTF204,2020-01-10,2031-01-01,38,1760798,<NA>,930.348258,937.40593,940.320868,916.20393,1000.0,<NA>,<NA>,<NA>,4,200000
216193,2024-09-06,NTN-F,950199,BRSTNCNTF212,2022-01-07,2033-01-01,20,309758,<NA>,916.517448,922.466269,930.200213,895.480003,1000.0,<NA>,<NA>,<NA>,0,0
216194,2024-09-06,NTN-F,950199,BRSTNCNTF238,2024-01-05,2035-01-01,26,523535,<NA>,903.712064,912.357687,916.194949,879.206445,1000.0,<NA>,<NA>,<NA>,3,150000