In [7]:
import pandas as pd

df = pd.read_parquet("../data/anbima_tpf.parquet")
df

,BondType,ReferenceDate,SelicCode,IssueBaseDate,MaturityDate,BDToMat,Duration,DV01,DV01USD,Price,BidRate,AskRate,IndicativeRate,DIRate,StdDev,LowerBoundRateD0,UpperBoundRateD0,LowerBoundRateD1,UpperBoundRateD1,Criteria
0,LFT,2020-01-02,210100,2000-07-01,2020-03-01,40,0.0,0.0,0.0,10471.849015,<NA>,<NA>,0.000023,0.04375,0.000307,0.000001,0.000051,0.000001,0.000051,Calculado
1,LFT,2020-01-02,210100,2000-07-01,2020-09-01,167,0.0,0.0,0.0,10471.723352,<NA>,<NA>,0.000023,0.04344,0.000307,0.000003,0.000044,0.000003,0.000045,Calculado
2,LFT,2020-01-02,210100,2000-07-01,2021-03-01,289,0.0,0.0,0.0,10471.356836,<NA>,<NA>,0.000044,0.046359,0.00031,0.00001,0.000064,0.000011,0.000064,Calculado
3,LFT,2020-01-02,210100,2000-07-01,2021-09-01,418,0.0,0.0,0.0,10470.917017,<NA>,<NA>,0.000056,0.050221,0.000357,0.000039,0.000077,0.00004,0.000077,Calculado
4,LFT,2020-01-02,210100,2000-07-01,2022-03-01,542,0.0,0.0,0.0,10470.016434,<NA>,<NA>,0.000083,0.053607,0.000322,0.00006,0.000102,0.00006,0.000101,Calculado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64295,NTN-F,2025-08-26,950199,2016-01-15,2027-01-01,339,1.275077,0.108567,0.020025,970.195537,0.139582,0.139328,0.13946,0.1398,0.001235,0.134653,0.142985,0.135247,0.143566,Calculado
64296,NTN-F,2025-08-26,950199,2018-01-05,2029-01-01,838,2.853494,0.234469,0.043248,931.709383,0.133983,0.133781,0.133895,0.13246,0.003567,0.128721,0.13864,0.129142,0.139062,Calculado
64297,NTN-F,2025-08-26,950199,2020-01-10,2031-01-01,1339,4.108755,0.318707,0.058786,882.82519,0.138196,0.138064,0.138133,0.13587,0.002094,0.133414,0.142937,0.133702,0.143225,Calculado
64298,NTN-F,2025-08-26,950199,2022-01-07,2033-01-01,1843,5.089522,0.379147,0.069934,848.53246,0.139154,0.13895,0.139038,0.13768,0.002832,0.134446,0.144068,0.134588,0.144212,Calculado
64299,NTN-F,2025-08-26,950199,2024-01-05,2035-01-01,2342,5.823301,0.418689,0.077228,819.856662,0.140404,0.140214,0.14029,0.13804,0.000289,0.1358,0.145356,0.135873,0.145433,Calculado

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64251 entries, 0 to 64250
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   BondType          64251 non-null  string
 1   ReferenceDate     64251 non-null  date32[day][pyarrow]
 2   SelicCode         64251 non-null  int64[pyarrow]
 3   IssueBaseDate     64251 non-null  date32[day][pyarrow]
 4   MaturityDate      64251 non-null  date32[day][pyarrow]
 5   BDToMat           64251 non-null  int64[pyarrow]
 6   Duration          64251 non-null  double[pyarrow]
 7   DV01              64251 non-null  double[pyarrow]
 8   DV01USD           64251 non-null  double[pyarrow]
 9   Price             64251 non-null  double[pyarrow]
 10  BidRate           61035 non-null  double[pyarrow]
 11  AskRate           61032 non-null  double[pyarrow]
 12  IndicativeRate    64251 non-null  double[pyarrow]
 13  DIRate            63813 non-null  double[pyarrow]
 14  StdDev            64251 non-null  double[pyarrow]
 15  LowerBoundRateD0  64202 non-null  double[pyarrow]
 16  UpperBoundRateD0  64202 non-null  double[pyarrow]
 17  LowerBoundRateD1  64206 non-null  double[pyarrow]
 18  UpperBoundRateD1  64206 non-null  double[pyarrow]
 19  Criteria          64251 non-null  string
dtypes: date32[day][pyarrow](3), double[pyarrow](13), int64[pyarrow](2), string(2)
memory usage: 10.0 MB

In [3]:
df.query("Price.notnull()")

       ReferenceDate BondType MaturityDate  IndicativeRate         Price
169807    2020-01-02      LFT   2020-03-01        0.000023  10471.849015
169808    2020-01-02      LFT   2020-09-01        0.000023  10471.723352
169809    2020-01-02      LFT   2021-03-01        0.000044  10471.356836
169810    2020-01-02      LFT   2021-09-01        0.000056  10470.917017
169811    2020-01-02      LFT   2022-03-01        0.000083  10470.016434
...              ...      ...          ...             ...           ...
233615    2025-08-25    NTN-F   2027-01-01        0.138871    970.334535
233616    2025-08-25    NTN-F   2029-01-01        0.133474    932.233659
233617    2025-08-25    NTN-F   2031-01-01        0.137845     883.29099
233618    2025-08-25    NTN-F   2033-01-01        0.138895    848.636792
233619    2025-08-25    NTN-F   2035-01-01        0.140215    819.743816

[63813 rows x 5 columns]

In [8]:
rdate = pd.to_datetime("03-01-2024", dayfirst=True)
df.query("ReferenceDate == @rdate").reset_index(drop=True)

   ReferenceDate BondType MaturityDate  IndicativeRate         Price
0     2024-01-03      LFT   2024-03-01        -0.00016  14282.392313
1     2024-01-03      LFT   2024-09-01       -0.000137  14283.334928
2     2024-01-03      LFT   2025-03-01        0.000014  14281.792468
3     2024-01-03      LFT   2025-09-01        0.000162  14278.193395
4     2024-01-03      LFT   2026-03-01        0.000411  14269.381379
5     2024-01-03      LFT   2026-09-01        0.000726  14254.499499
6     2024-01-03      LFT   2027-03-01        0.001206  14228.092015
7     2024-01-03      LFT   2027-09-01        0.001305  14214.195595
8     2024-01-03      LFT   2028-03-01        0.001374  14201.013276
9     2024-01-03      LFT   2028-09-01        0.001483  14183.931962
10    2024-01-03      LFT   2029-03-01        0.001606  14165.008266
11    2024-01-03      LFT   2029-09-01        0.001677  14147.727003
12    2024-01-03      LTN   2024-04-01        0.111034    975.242313
13    2024-01-03      LTN   2024-07-01        0.106105    951.969879
14    2024-01-03      LTN   2024-10-01        0.101534    930.039876
15    2024-01-03      LTN   2025-01-01        0.098623    910.230351
16    2024-01-03      LTN   2025-04-01        0.098665    889.698208
17    2024-01-03      LTN   2025-07-01        0.097795    870.685519
18    2024-01-03      LTN   2025-10-01        0.097528    850.027672
19    2024-01-03      LTN   2026-01-01         0.09715    830.745476
20    2024-01-03      LTN   2026-07-01        0.097955     792.83506
21    2024-01-03      LTN   2027-07-01        0.099889    718.229917
22    2024-01-03    NTN-B   2024-08-15        0.064763   4266.019173
23    2024-01-03    NTN-B   2025-05-15          0.0544   4247.937379
24    2024-01-03    NTN-B   2026-08-15        0.051766   4359.557528
25    2024-01-03    NTN-B   2027-05-15          0.0526   4311.562537
26    2024-01-03    NTN-B   2028-08-15         0.05227    4409.17578
27    2024-01-03    NTN-B   2030-08-15          0.0522   4461.454842
28    2024-01-03    NTN-B   2032-08-15        0.053212   4474.993178
29    2024-01-03    NTN-B   2033-05-15        0.053142   4429.449814
30    2024-01-03    NTN-B   2035-05-15         0.05348   4452.200578
31    2024-01-03    NTN-B   2040-08-15        0.053735   4570.338875
32    2024-01-03    NTN-B   2045-05-15        0.054804   4499.070163
33    2024-01-03    NTN-B   2050-08-15        0.054784   4594.344737
34    2024-01-03    NTN-B   2055-05-15          0.0548   4555.001564
35    2024-01-03    NTN-B   2060-08-15        0.054948   4625.061197
36    2024-01-03    NTN-C   2031-01-01        0.055269   8319.419694
37    2024-01-03    NTN-F   2025-01-01        0.098702   1001.206109
38    2024-01-03    NTN-F   2027-01-01        0.098851   1003.857578
39    2024-01-03    NTN-F   2029-01-01        0.101938      995.2765
40    2024-01-03    NTN-F   2031-01-01        0.103929    984.719625
41    2024-01-03    NTN-F   2033-01-01        0.104724    977.127029

In [ ]:
# df.to_parquet("../data/anbima_tpf.parquet", index=False, compression="gzip")